/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-16143
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// InventoryGenericInventoryRelationship - A relationship to the 'inventory.GenericInventory' resource, or the expanded 'inventory.GenericInventory' resource, or the 'null' value.
type InventoryGenericInventoryRelationship struct {
	InventoryGenericInventory *InventoryGenericInventory
	MoMoRef                   *MoMoRef
}

// InventoryGenericInventoryAsInventoryGenericInventoryRelationship is a convenience function that returns InventoryGenericInventory wrapped in InventoryGenericInventoryRelationship
func InventoryGenericInventoryAsInventoryGenericInventoryRelationship(v *InventoryGenericInventory) InventoryGenericInventoryRelationship {
	return InventoryGenericInventoryRelationship{
		InventoryGenericInventory: v,
	}
}

// MoMoRefAsInventoryGenericInventoryRelationship is a convenience function that returns MoMoRef wrapped in InventoryGenericInventoryRelationship
func MoMoRefAsInventoryGenericInventoryRelationship(v *MoMoRef) InventoryGenericInventoryRelationship {
	return InventoryGenericInventoryRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *InventoryGenericInventoryRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'inventory.GenericInventory'
	if jsonDict["ClassId"] == "inventory.GenericInventory" {
		// try to unmarshal JSON data into InventoryGenericInventory
		err = json.Unmarshal(data, &dst.InventoryGenericInventory)
		if err == nil {
			return nil // data stored in dst.InventoryGenericInventory, return on the first match
		} else {
			dst.InventoryGenericInventory = nil
			return fmt.Errorf("failed to unmarshal InventoryGenericInventoryRelationship as InventoryGenericInventory: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal InventoryGenericInventoryRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InventoryGenericInventoryRelationship) MarshalJSON() ([]byte, error) {
	if src.InventoryGenericInventory != nil {
		return json.Marshal(&src.InventoryGenericInventory)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *InventoryGenericInventoryRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.InventoryGenericInventory != nil {
		return obj.InventoryGenericInventory
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableInventoryGenericInventoryRelationship struct {
	value *InventoryGenericInventoryRelationship
	isSet bool
}

func (v NullableInventoryGenericInventoryRelationship) Get() *InventoryGenericInventoryRelationship {
	return v.value
}

func (v *NullableInventoryGenericInventoryRelationship) Set(val *InventoryGenericInventoryRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryGenericInventoryRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryGenericInventoryRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryGenericInventoryRelationship(val *InventoryGenericInventoryRelationship) *NullableInventoryGenericInventoryRelationship {
	return &NullableInventoryGenericInventoryRelationship{value: val, isSet: true}
}

func (v NullableInventoryGenericInventoryRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryGenericInventoryRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
