/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2026030305
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// ApplianceFileSystemOpSummaryRelationship - A relationship to the 'appliance.FileSystemOpSummary' resource, or the expanded 'appliance.FileSystemOpSummary' resource, or the 'null' value.
type ApplianceFileSystemOpSummaryRelationship struct {
	ApplianceFileSystemOpSummary *ApplianceFileSystemOpSummary
	MoMoRef                      *MoMoRef
}

// ApplianceFileSystemOpSummaryAsApplianceFileSystemOpSummaryRelationship is a convenience function that returns ApplianceFileSystemOpSummary wrapped in ApplianceFileSystemOpSummaryRelationship
func ApplianceFileSystemOpSummaryAsApplianceFileSystemOpSummaryRelationship(v *ApplianceFileSystemOpSummary) ApplianceFileSystemOpSummaryRelationship {
	return ApplianceFileSystemOpSummaryRelationship{
		ApplianceFileSystemOpSummary: v,
	}
}

// MoMoRefAsApplianceFileSystemOpSummaryRelationship is a convenience function that returns MoMoRef wrapped in ApplianceFileSystemOpSummaryRelationship
func MoMoRefAsApplianceFileSystemOpSummaryRelationship(v *MoMoRef) ApplianceFileSystemOpSummaryRelationship {
	return ApplianceFileSystemOpSummaryRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ApplianceFileSystemOpSummaryRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'appliance.FileSystemOpSummary'
	if jsonDict["ClassId"] == "appliance.FileSystemOpSummary" {
		// try to unmarshal JSON data into ApplianceFileSystemOpSummary
		err = json.Unmarshal(data, &dst.ApplianceFileSystemOpSummary)
		if err == nil {
			return nil // data stored in dst.ApplianceFileSystemOpSummary, return on the first match
		} else {
			dst.ApplianceFileSystemOpSummary = nil
			return fmt.Errorf("failed to unmarshal ApplianceFileSystemOpSummaryRelationship as ApplianceFileSystemOpSummary: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal ApplianceFileSystemOpSummaryRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ApplianceFileSystemOpSummaryRelationship) MarshalJSON() ([]byte, error) {
	if src.ApplianceFileSystemOpSummary != nil {
		return json.Marshal(&src.ApplianceFileSystemOpSummary)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ApplianceFileSystemOpSummaryRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ApplianceFileSystemOpSummary != nil {
		return obj.ApplianceFileSystemOpSummary
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableApplianceFileSystemOpSummaryRelationship struct {
	value *ApplianceFileSystemOpSummaryRelationship
	isSet bool
}

func (v NullableApplianceFileSystemOpSummaryRelationship) Get() *ApplianceFileSystemOpSummaryRelationship {
	return v.value
}

func (v *NullableApplianceFileSystemOpSummaryRelationship) Set(val *ApplianceFileSystemOpSummaryRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableApplianceFileSystemOpSummaryRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableApplianceFileSystemOpSummaryRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplianceFileSystemOpSummaryRelationship(val *ApplianceFileSystemOpSummaryRelationship) *NullableApplianceFileSystemOpSummaryRelationship {
	return &NullableApplianceFileSystemOpSummaryRelationship{value: val, isSet: true}
}

func (v NullableApplianceFileSystemOpSummaryRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplianceFileSystemOpSummaryRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
