/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025081401
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// FabricServerRoleResponse - The response body of a HTTP GET request for the 'fabric.ServerRole' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'fabric.ServerRole' resources.
type FabricServerRoleResponse struct {
	FabricServerRoleList *FabricServerRoleList
	MoAggregateTransform *MoAggregateTransform
	MoDocumentCount      *MoDocumentCount
	MoTagSummary         *MoTagSummary
}

// FabricServerRoleListAsFabricServerRoleResponse is a convenience function that returns FabricServerRoleList wrapped in FabricServerRoleResponse
func FabricServerRoleListAsFabricServerRoleResponse(v *FabricServerRoleList) FabricServerRoleResponse {
	return FabricServerRoleResponse{
		FabricServerRoleList: v,
	}
}

// MoAggregateTransformAsFabricServerRoleResponse is a convenience function that returns MoAggregateTransform wrapped in FabricServerRoleResponse
func MoAggregateTransformAsFabricServerRoleResponse(v *MoAggregateTransform) FabricServerRoleResponse {
	return FabricServerRoleResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsFabricServerRoleResponse is a convenience function that returns MoDocumentCount wrapped in FabricServerRoleResponse
func MoDocumentCountAsFabricServerRoleResponse(v *MoDocumentCount) FabricServerRoleResponse {
	return FabricServerRoleResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsFabricServerRoleResponse is a convenience function that returns MoTagSummary wrapped in FabricServerRoleResponse
func MoTagSummaryAsFabricServerRoleResponse(v *MoTagSummary) FabricServerRoleResponse {
	return FabricServerRoleResponse{
		MoTagSummary: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *FabricServerRoleResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'fabric.ServerRole.List'
	if jsonDict["ObjectType"] == "fabric.ServerRole.List" {
		// try to unmarshal JSON data into FabricServerRoleList
		err = json.Unmarshal(data, &dst.FabricServerRoleList)
		if err == nil {
			return nil // data stored in dst.FabricServerRoleList, return on the first match
		} else {
			dst.FabricServerRoleList = nil
			return fmt.Errorf("failed to unmarshal FabricServerRoleResponse as FabricServerRoleList: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal FabricServerRoleResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal FabricServerRoleResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal FabricServerRoleResponse as MoTagSummary: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FabricServerRoleResponse) MarshalJSON() ([]byte, error) {
	if src.FabricServerRoleList != nil {
		return json.Marshal(&src.FabricServerRoleList)
	}

	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FabricServerRoleResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FabricServerRoleList != nil {
		return obj.FabricServerRoleList
	}

	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	// all schemas are nil
	return nil
}

type NullableFabricServerRoleResponse struct {
	value *FabricServerRoleResponse
	isSet bool
}

func (v NullableFabricServerRoleResponse) Get() *FabricServerRoleResponse {
	return v.value
}

func (v *NullableFabricServerRoleResponse) Set(val *FabricServerRoleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFabricServerRoleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFabricServerRoleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFabricServerRoleResponse(val *FabricServerRoleResponse) *NullableFabricServerRoleResponse {
	return &NullableFabricServerRoleResponse{value: val, isSet: true}
}

func (v NullableFabricServerRoleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFabricServerRoleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
