/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-18534
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// BootNvmeDeviceRelationship - A relationship to the 'boot.NvmeDevice' resource, or the expanded 'boot.NvmeDevice' resource, or the 'null' value.
type BootNvmeDeviceRelationship struct {
	BootNvmeDevice *BootNvmeDevice
	MoMoRef        *MoMoRef
}

// BootNvmeDeviceAsBootNvmeDeviceRelationship is a convenience function that returns BootNvmeDevice wrapped in BootNvmeDeviceRelationship
func BootNvmeDeviceAsBootNvmeDeviceRelationship(v *BootNvmeDevice) BootNvmeDeviceRelationship {
	return BootNvmeDeviceRelationship{
		BootNvmeDevice: v,
	}
}

// MoMoRefAsBootNvmeDeviceRelationship is a convenience function that returns MoMoRef wrapped in BootNvmeDeviceRelationship
func MoMoRefAsBootNvmeDeviceRelationship(v *MoMoRef) BootNvmeDeviceRelationship {
	return BootNvmeDeviceRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BootNvmeDeviceRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'boot.NvmeDevice'
	if jsonDict["ClassId"] == "boot.NvmeDevice" {
		// try to unmarshal JSON data into BootNvmeDevice
		err = json.Unmarshal(data, &dst.BootNvmeDevice)
		if err == nil {
			return nil // data stored in dst.BootNvmeDevice, return on the first match
		} else {
			dst.BootNvmeDevice = nil
			return fmt.Errorf("failed to unmarshal BootNvmeDeviceRelationship as BootNvmeDevice: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal BootNvmeDeviceRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BootNvmeDeviceRelationship) MarshalJSON() ([]byte, error) {
	if src.BootNvmeDevice != nil {
		return json.Marshal(&src.BootNvmeDevice)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BootNvmeDeviceRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BootNvmeDevice != nil {
		return obj.BootNvmeDevice
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableBootNvmeDeviceRelationship struct {
	value *BootNvmeDeviceRelationship
	isSet bool
}

func (v NullableBootNvmeDeviceRelationship) Get() *BootNvmeDeviceRelationship {
	return v.value
}

func (v *NullableBootNvmeDeviceRelationship) Set(val *BootNvmeDeviceRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableBootNvmeDeviceRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableBootNvmeDeviceRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBootNvmeDeviceRelationship(val *BootNvmeDeviceRelationship) *NullableBootNvmeDeviceRelationship {
	return &NullableBootNvmeDeviceRelationship{value: val, isSet: true}
}

func (v NullableBootNvmeDeviceRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBootNvmeDeviceRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
