/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025040411
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the NiaapiDcnmSweol type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NiaapiDcnmSweol{}

// NiaapiDcnmSweol The software end of life notice for DCNM.
type NiaapiDcnmSweol struct {
	NiaapiSoftwareEol
	AdditionalProperties map[string]interface{}
}

type _NiaapiDcnmSweol NiaapiDcnmSweol

// NewNiaapiDcnmSweol instantiates a new NiaapiDcnmSweol object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNiaapiDcnmSweol(classId string, objectType string) *NiaapiDcnmSweol {
	this := NiaapiDcnmSweol{}
	this.ClassId = classId
	this.ObjectType = objectType
	return &this
}

// NewNiaapiDcnmSweolWithDefaults instantiates a new NiaapiDcnmSweol object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNiaapiDcnmSweolWithDefaults() *NiaapiDcnmSweol {
	this := NiaapiDcnmSweol{}
	return &this
}

func (o NiaapiDcnmSweol) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NiaapiDcnmSweol) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedNiaapiSoftwareEol, errNiaapiSoftwareEol := json.Marshal(o.NiaapiSoftwareEol)
	if errNiaapiSoftwareEol != nil {
		return map[string]interface{}{}, errNiaapiSoftwareEol
	}
	errNiaapiSoftwareEol = json.Unmarshal([]byte(serializedNiaapiSoftwareEol), &toSerialize)
	if errNiaapiSoftwareEol != nil {
		return map[string]interface{}{}, errNiaapiSoftwareEol
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NiaapiDcnmSweol) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ClassId",
		"ObjectType",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	type NiaapiDcnmSweolWithoutEmbeddedStruct struct {
	}

	varNiaapiDcnmSweolWithoutEmbeddedStruct := NiaapiDcnmSweolWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varNiaapiDcnmSweolWithoutEmbeddedStruct)
	if err == nil {
		varNiaapiDcnmSweol := _NiaapiDcnmSweol{}
		*o = NiaapiDcnmSweol(varNiaapiDcnmSweol)
	} else {
		return err
	}

	varNiaapiDcnmSweol := _NiaapiDcnmSweol{}

	err = json.Unmarshal(data, &varNiaapiDcnmSweol)
	if err == nil {
		o.NiaapiSoftwareEol = varNiaapiDcnmSweol.NiaapiSoftwareEol
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectNiaapiSoftwareEol := reflect.ValueOf(o.NiaapiSoftwareEol)
		for i := 0; i < reflectNiaapiSoftwareEol.Type().NumField(); i++ {
			t := reflectNiaapiSoftwareEol.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNiaapiDcnmSweol struct {
	value *NiaapiDcnmSweol
	isSet bool
}

func (v NullableNiaapiDcnmSweol) Get() *NiaapiDcnmSweol {
	return v.value
}

func (v *NullableNiaapiDcnmSweol) Set(val *NiaapiDcnmSweol) {
	v.value = val
	v.isSet = true
}

func (v NullableNiaapiDcnmSweol) IsSet() bool {
	return v.isSet
}

func (v *NullableNiaapiDcnmSweol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNiaapiDcnmSweol(val *NiaapiDcnmSweol) *NullableNiaapiDcnmSweol {
	return &NullableNiaapiDcnmSweol{value: val, isSet: true}
}

func (v NullableNiaapiDcnmSweol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNiaapiDcnmSweol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
