/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025102807
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// SchedulerSchedulePolicyRelationship - A relationship to the 'scheduler.SchedulePolicy' resource, or the expanded 'scheduler.SchedulePolicy' resource, or the 'null' value.
type SchedulerSchedulePolicyRelationship struct {
	MoMoRef                 *MoMoRef
	SchedulerSchedulePolicy *SchedulerSchedulePolicy
}

// MoMoRefAsSchedulerSchedulePolicyRelationship is a convenience function that returns MoMoRef wrapped in SchedulerSchedulePolicyRelationship
func MoMoRefAsSchedulerSchedulePolicyRelationship(v *MoMoRef) SchedulerSchedulePolicyRelationship {
	return SchedulerSchedulePolicyRelationship{
		MoMoRef: v,
	}
}

// SchedulerSchedulePolicyAsSchedulerSchedulePolicyRelationship is a convenience function that returns SchedulerSchedulePolicy wrapped in SchedulerSchedulePolicyRelationship
func SchedulerSchedulePolicyAsSchedulerSchedulePolicyRelationship(v *SchedulerSchedulePolicy) SchedulerSchedulePolicyRelationship {
	return SchedulerSchedulePolicyRelationship{
		SchedulerSchedulePolicy: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *SchedulerSchedulePolicyRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal SchedulerSchedulePolicyRelationship as MoMoRef: %s", err.Error())
		}
	}

	// check if the discriminator value is 'scheduler.SchedulePolicy'
	if jsonDict["ClassId"] == "scheduler.SchedulePolicy" {
		// try to unmarshal JSON data into SchedulerSchedulePolicy
		err = json.Unmarshal(data, &dst.SchedulerSchedulePolicy)
		if err == nil {
			return nil // data stored in dst.SchedulerSchedulePolicy, return on the first match
		} else {
			dst.SchedulerSchedulePolicy = nil
			return fmt.Errorf("failed to unmarshal SchedulerSchedulePolicyRelationship as SchedulerSchedulePolicy: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SchedulerSchedulePolicyRelationship) MarshalJSON() ([]byte, error) {
	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	if src.SchedulerSchedulePolicy != nil {
		return json.Marshal(&src.SchedulerSchedulePolicy)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SchedulerSchedulePolicyRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	if obj.SchedulerSchedulePolicy != nil {
		return obj.SchedulerSchedulePolicy
	}

	// all schemas are nil
	return nil
}

type NullableSchedulerSchedulePolicyRelationship struct {
	value *SchedulerSchedulePolicyRelationship
	isSet bool
}

func (v NullableSchedulerSchedulePolicyRelationship) Get() *SchedulerSchedulePolicyRelationship {
	return v.value
}

func (v *NullableSchedulerSchedulePolicyRelationship) Set(val *SchedulerSchedulePolicyRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableSchedulerSchedulePolicyRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableSchedulerSchedulePolicyRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchedulerSchedulePolicyRelationship(val *SchedulerSchedulePolicyRelationship) *NullableSchedulerSchedulePolicyRelationship {
	return &NullableSchedulerSchedulePolicyRelationship{value: val, isSet: true}
}

func (v NullableSchedulerSchedulePolicyRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchedulerSchedulePolicyRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
