/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-17057
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// FabricVlanSetRelationship - A relationship to the 'fabric.VlanSet' resource, or the expanded 'fabric.VlanSet' resource, or the 'null' value.
type FabricVlanSetRelationship struct {
	FabricVlanSet *FabricVlanSet
	MoMoRef       *MoMoRef
}

// FabricVlanSetAsFabricVlanSetRelationship is a convenience function that returns FabricVlanSet wrapped in FabricVlanSetRelationship
func FabricVlanSetAsFabricVlanSetRelationship(v *FabricVlanSet) FabricVlanSetRelationship {
	return FabricVlanSetRelationship{
		FabricVlanSet: v,
	}
}

// MoMoRefAsFabricVlanSetRelationship is a convenience function that returns MoMoRef wrapped in FabricVlanSetRelationship
func MoMoRefAsFabricVlanSetRelationship(v *MoMoRef) FabricVlanSetRelationship {
	return FabricVlanSetRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *FabricVlanSetRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'fabric.VlanSet'
	if jsonDict["ClassId"] == "fabric.VlanSet" {
		// try to unmarshal JSON data into FabricVlanSet
		err = json.Unmarshal(data, &dst.FabricVlanSet)
		if err == nil {
			return nil // data stored in dst.FabricVlanSet, return on the first match
		} else {
			dst.FabricVlanSet = nil
			return fmt.Errorf("failed to unmarshal FabricVlanSetRelationship as FabricVlanSet: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal FabricVlanSetRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FabricVlanSetRelationship) MarshalJSON() ([]byte, error) {
	if src.FabricVlanSet != nil {
		return json.Marshal(&src.FabricVlanSet)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FabricVlanSetRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FabricVlanSet != nil {
		return obj.FabricVlanSet
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableFabricVlanSetRelationship struct {
	value *FabricVlanSetRelationship
	isSet bool
}

func (v NullableFabricVlanSetRelationship) Get() *FabricVlanSetRelationship {
	return v.value
}

func (v *NullableFabricVlanSetRelationship) Set(val *FabricVlanSetRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableFabricVlanSetRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableFabricVlanSetRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFabricVlanSetRelationship(val *FabricVlanSetRelationship) *NullableFabricVlanSetRelationship {
	return &NullableFabricVlanSetRelationship{value: val, isSet: true}
}

func (v NullableFabricVlanSetRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFabricVlanSetRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
