/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-16711
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// ConsoleConsoleConfigRelationship - A relationship to the 'console.ConsoleConfig' resource, or the expanded 'console.ConsoleConfig' resource, or the 'null' value.
type ConsoleConsoleConfigRelationship struct {
	ConsoleConsoleConfig *ConsoleConsoleConfig
	MoMoRef              *MoMoRef
}

// ConsoleConsoleConfigAsConsoleConsoleConfigRelationship is a convenience function that returns ConsoleConsoleConfig wrapped in ConsoleConsoleConfigRelationship
func ConsoleConsoleConfigAsConsoleConsoleConfigRelationship(v *ConsoleConsoleConfig) ConsoleConsoleConfigRelationship {
	return ConsoleConsoleConfigRelationship{
		ConsoleConsoleConfig: v,
	}
}

// MoMoRefAsConsoleConsoleConfigRelationship is a convenience function that returns MoMoRef wrapped in ConsoleConsoleConfigRelationship
func MoMoRefAsConsoleConsoleConfigRelationship(v *MoMoRef) ConsoleConsoleConfigRelationship {
	return ConsoleConsoleConfigRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ConsoleConsoleConfigRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'console.ConsoleConfig'
	if jsonDict["ClassId"] == "console.ConsoleConfig" {
		// try to unmarshal JSON data into ConsoleConsoleConfig
		err = json.Unmarshal(data, &dst.ConsoleConsoleConfig)
		if err == nil {
			return nil // data stored in dst.ConsoleConsoleConfig, return on the first match
		} else {
			dst.ConsoleConsoleConfig = nil
			return fmt.Errorf("failed to unmarshal ConsoleConsoleConfigRelationship as ConsoleConsoleConfig: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal ConsoleConsoleConfigRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ConsoleConsoleConfigRelationship) MarshalJSON() ([]byte, error) {
	if src.ConsoleConsoleConfig != nil {
		return json.Marshal(&src.ConsoleConsoleConfig)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ConsoleConsoleConfigRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ConsoleConsoleConfig != nil {
		return obj.ConsoleConsoleConfig
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableConsoleConsoleConfigRelationship struct {
	value *ConsoleConsoleConfigRelationship
	isSet bool
}

func (v NullableConsoleConsoleConfigRelationship) Get() *ConsoleConsoleConfigRelationship {
	return v.value
}

func (v *NullableConsoleConsoleConfigRelationship) Set(val *ConsoleConsoleConfigRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableConsoleConsoleConfigRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableConsoleConsoleConfigRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsoleConsoleConfigRelationship(val *ConsoleConsoleConfigRelationship) *NullableConsoleConsoleConfigRelationship {
	return &NullableConsoleConsoleConfigRelationship{value: val, isSet: true}
}

func (v NullableConsoleConsoleConfigRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsoleConsoleConfigRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
