/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2024112619
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the StorageNetAppPerformanceMetricsAverage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageNetAppPerformanceMetricsAverage{}

// StorageNetAppPerformanceMetricsAverage Average performance metrics data for a NetApp storage resource over a given period of time.
type StorageNetAppPerformanceMetricsAverage struct {
	StorageBasePerformanceMetricsAverage
	AdditionalProperties map[string]interface{}
}

type _StorageNetAppPerformanceMetricsAverage StorageNetAppPerformanceMetricsAverage

// NewStorageNetAppPerformanceMetricsAverage instantiates a new StorageNetAppPerformanceMetricsAverage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageNetAppPerformanceMetricsAverage(classId string, objectType string) *StorageNetAppPerformanceMetricsAverage {
	this := StorageNetAppPerformanceMetricsAverage{}
	this.ClassId = classId
	this.ObjectType = objectType
	return &this
}

// NewStorageNetAppPerformanceMetricsAverageWithDefaults instantiates a new StorageNetAppPerformanceMetricsAverage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageNetAppPerformanceMetricsAverageWithDefaults() *StorageNetAppPerformanceMetricsAverage {
	this := StorageNetAppPerformanceMetricsAverage{}
	return &this
}

func (o StorageNetAppPerformanceMetricsAverage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageNetAppPerformanceMetricsAverage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedStorageBasePerformanceMetricsAverage, errStorageBasePerformanceMetricsAverage := json.Marshal(o.StorageBasePerformanceMetricsAverage)
	if errStorageBasePerformanceMetricsAverage != nil {
		return map[string]interface{}{}, errStorageBasePerformanceMetricsAverage
	}
	errStorageBasePerformanceMetricsAverage = json.Unmarshal([]byte(serializedStorageBasePerformanceMetricsAverage), &toSerialize)
	if errStorageBasePerformanceMetricsAverage != nil {
		return map[string]interface{}{}, errStorageBasePerformanceMetricsAverage
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StorageNetAppPerformanceMetricsAverage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ClassId",
		"ObjectType",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{
		"ClassId":    o.GetDefaultClassId,
		"ObjectType": o.GetDefaultObjectType,
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	type StorageNetAppPerformanceMetricsAverageWithoutEmbeddedStruct struct {
	}

	varStorageNetAppPerformanceMetricsAverageWithoutEmbeddedStruct := StorageNetAppPerformanceMetricsAverageWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varStorageNetAppPerformanceMetricsAverageWithoutEmbeddedStruct)
	if err == nil {
		varStorageNetAppPerformanceMetricsAverage := _StorageNetAppPerformanceMetricsAverage{}
		*o = StorageNetAppPerformanceMetricsAverage(varStorageNetAppPerformanceMetricsAverage)
	} else {
		return err
	}

	varStorageNetAppPerformanceMetricsAverage := _StorageNetAppPerformanceMetricsAverage{}

	err = json.Unmarshal(data, &varStorageNetAppPerformanceMetricsAverage)
	if err == nil {
		o.StorageBasePerformanceMetricsAverage = varStorageNetAppPerformanceMetricsAverage.StorageBasePerformanceMetricsAverage
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectStorageBasePerformanceMetricsAverage := reflect.ValueOf(o.StorageBasePerformanceMetricsAverage)
		for i := 0; i < reflectStorageBasePerformanceMetricsAverage.Type().NumField(); i++ {
			t := reflectStorageBasePerformanceMetricsAverage.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStorageNetAppPerformanceMetricsAverage struct {
	value *StorageNetAppPerformanceMetricsAverage
	isSet bool
}

func (v NullableStorageNetAppPerformanceMetricsAverage) Get() *StorageNetAppPerformanceMetricsAverage {
	return v.value
}

func (v *NullableStorageNetAppPerformanceMetricsAverage) Set(val *StorageNetAppPerformanceMetricsAverage) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageNetAppPerformanceMetricsAverage) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageNetAppPerformanceMetricsAverage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageNetAppPerformanceMetricsAverage(val *StorageNetAppPerformanceMetricsAverage) *NullableStorageNetAppPerformanceMetricsAverage {
	return &NullableStorageNetAppPerformanceMetricsAverage{value: val, isSet: true}
}

func (v NullableStorageNetAppPerformanceMetricsAverage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageNetAppPerformanceMetricsAverage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
