/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025051220
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// FabricSpanSourceVnicEthIfResponse - The response body of a HTTP GET request for the 'fabric.SpanSourceVnicEthIf' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'fabric.SpanSourceVnicEthIf' resources.
type FabricSpanSourceVnicEthIfResponse struct {
	FabricSpanSourceVnicEthIfList *FabricSpanSourceVnicEthIfList
	MoAggregateTransform          *MoAggregateTransform
	MoDocumentCount               *MoDocumentCount
	MoTagSummary                  *MoTagSummary
}

// FabricSpanSourceVnicEthIfListAsFabricSpanSourceVnicEthIfResponse is a convenience function that returns FabricSpanSourceVnicEthIfList wrapped in FabricSpanSourceVnicEthIfResponse
func FabricSpanSourceVnicEthIfListAsFabricSpanSourceVnicEthIfResponse(v *FabricSpanSourceVnicEthIfList) FabricSpanSourceVnicEthIfResponse {
	return FabricSpanSourceVnicEthIfResponse{
		FabricSpanSourceVnicEthIfList: v,
	}
}

// MoAggregateTransformAsFabricSpanSourceVnicEthIfResponse is a convenience function that returns MoAggregateTransform wrapped in FabricSpanSourceVnicEthIfResponse
func MoAggregateTransformAsFabricSpanSourceVnicEthIfResponse(v *MoAggregateTransform) FabricSpanSourceVnicEthIfResponse {
	return FabricSpanSourceVnicEthIfResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsFabricSpanSourceVnicEthIfResponse is a convenience function that returns MoDocumentCount wrapped in FabricSpanSourceVnicEthIfResponse
func MoDocumentCountAsFabricSpanSourceVnicEthIfResponse(v *MoDocumentCount) FabricSpanSourceVnicEthIfResponse {
	return FabricSpanSourceVnicEthIfResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsFabricSpanSourceVnicEthIfResponse is a convenience function that returns MoTagSummary wrapped in FabricSpanSourceVnicEthIfResponse
func MoTagSummaryAsFabricSpanSourceVnicEthIfResponse(v *MoTagSummary) FabricSpanSourceVnicEthIfResponse {
	return FabricSpanSourceVnicEthIfResponse{
		MoTagSummary: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *FabricSpanSourceVnicEthIfResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'fabric.SpanSourceVnicEthIf.List'
	if jsonDict["ObjectType"] == "fabric.SpanSourceVnicEthIf.List" {
		// try to unmarshal JSON data into FabricSpanSourceVnicEthIfList
		err = json.Unmarshal(data, &dst.FabricSpanSourceVnicEthIfList)
		if err == nil {
			return nil // data stored in dst.FabricSpanSourceVnicEthIfList, return on the first match
		} else {
			dst.FabricSpanSourceVnicEthIfList = nil
			return fmt.Errorf("failed to unmarshal FabricSpanSourceVnicEthIfResponse as FabricSpanSourceVnicEthIfList: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal FabricSpanSourceVnicEthIfResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal FabricSpanSourceVnicEthIfResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal FabricSpanSourceVnicEthIfResponse as MoTagSummary: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FabricSpanSourceVnicEthIfResponse) MarshalJSON() ([]byte, error) {
	if src.FabricSpanSourceVnicEthIfList != nil {
		return json.Marshal(&src.FabricSpanSourceVnicEthIfList)
	}

	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FabricSpanSourceVnicEthIfResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FabricSpanSourceVnicEthIfList != nil {
		return obj.FabricSpanSourceVnicEthIfList
	}

	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	// all schemas are nil
	return nil
}

type NullableFabricSpanSourceVnicEthIfResponse struct {
	value *FabricSpanSourceVnicEthIfResponse
	isSet bool
}

func (v NullableFabricSpanSourceVnicEthIfResponse) Get() *FabricSpanSourceVnicEthIfResponse {
	return v.value
}

func (v *NullableFabricSpanSourceVnicEthIfResponse) Set(val *FabricSpanSourceVnicEthIfResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFabricSpanSourceVnicEthIfResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFabricSpanSourceVnicEthIfResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFabricSpanSourceVnicEthIfResponse(val *FabricSpanSourceVnicEthIfResponse) *NullableFabricSpanSourceVnicEthIfResponse {
	return &NullableFabricSpanSourceVnicEthIfResponse{value: val, isSet: true}
}

func (v NullableFabricSpanSourceVnicEthIfResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFabricSpanSourceVnicEthIfResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
