/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025030309
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// HyperflexSoftwareDistributionVersionRelationship - A relationship to the 'hyperflex.SoftwareDistributionVersion' resource, or the expanded 'hyperflex.SoftwareDistributionVersion' resource, or the 'null' value.
type HyperflexSoftwareDistributionVersionRelationship struct {
	HyperflexSoftwareDistributionVersion *HyperflexSoftwareDistributionVersion
	MoMoRef                              *MoMoRef
}

// HyperflexSoftwareDistributionVersionAsHyperflexSoftwareDistributionVersionRelationship is a convenience function that returns HyperflexSoftwareDistributionVersion wrapped in HyperflexSoftwareDistributionVersionRelationship
func HyperflexSoftwareDistributionVersionAsHyperflexSoftwareDistributionVersionRelationship(v *HyperflexSoftwareDistributionVersion) HyperflexSoftwareDistributionVersionRelationship {
	return HyperflexSoftwareDistributionVersionRelationship{
		HyperflexSoftwareDistributionVersion: v,
	}
}

// MoMoRefAsHyperflexSoftwareDistributionVersionRelationship is a convenience function that returns MoMoRef wrapped in HyperflexSoftwareDistributionVersionRelationship
func MoMoRefAsHyperflexSoftwareDistributionVersionRelationship(v *MoMoRef) HyperflexSoftwareDistributionVersionRelationship {
	return HyperflexSoftwareDistributionVersionRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *HyperflexSoftwareDistributionVersionRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'hyperflex.SoftwareDistributionVersion'
	if jsonDict["ClassId"] == "hyperflex.SoftwareDistributionVersion" {
		// try to unmarshal JSON data into HyperflexSoftwareDistributionVersion
		err = json.Unmarshal(data, &dst.HyperflexSoftwareDistributionVersion)
		if err == nil {
			return nil // data stored in dst.HyperflexSoftwareDistributionVersion, return on the first match
		} else {
			dst.HyperflexSoftwareDistributionVersion = nil
			return fmt.Errorf("failed to unmarshal HyperflexSoftwareDistributionVersionRelationship as HyperflexSoftwareDistributionVersion: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal HyperflexSoftwareDistributionVersionRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src HyperflexSoftwareDistributionVersionRelationship) MarshalJSON() ([]byte, error) {
	if src.HyperflexSoftwareDistributionVersion != nil {
		return json.Marshal(&src.HyperflexSoftwareDistributionVersion)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *HyperflexSoftwareDistributionVersionRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.HyperflexSoftwareDistributionVersion != nil {
		return obj.HyperflexSoftwareDistributionVersion
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableHyperflexSoftwareDistributionVersionRelationship struct {
	value *HyperflexSoftwareDistributionVersionRelationship
	isSet bool
}

func (v NullableHyperflexSoftwareDistributionVersionRelationship) Get() *HyperflexSoftwareDistributionVersionRelationship {
	return v.value
}

func (v *NullableHyperflexSoftwareDistributionVersionRelationship) Set(val *HyperflexSoftwareDistributionVersionRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableHyperflexSoftwareDistributionVersionRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableHyperflexSoftwareDistributionVersionRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHyperflexSoftwareDistributionVersionRelationship(val *HyperflexSoftwareDistributionVersionRelationship) *NullableHyperflexSoftwareDistributionVersionRelationship {
	return &NullableHyperflexSoftwareDistributionVersionRelationship{value: val, isSet: true}
}

func (v NullableHyperflexSoftwareDistributionVersionRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHyperflexSoftwareDistributionVersionRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
