/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025051220
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// ApplianceAppStatusResponse - The response body of a HTTP GET request for the 'appliance.AppStatus' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'appliance.AppStatus' resources.
type ApplianceAppStatusResponse struct {
	ApplianceAppStatusList *ApplianceAppStatusList
	MoAggregateTransform   *MoAggregateTransform
	MoDocumentCount        *MoDocumentCount
	MoTagSummary           *MoTagSummary
}

// ApplianceAppStatusListAsApplianceAppStatusResponse is a convenience function that returns ApplianceAppStatusList wrapped in ApplianceAppStatusResponse
func ApplianceAppStatusListAsApplianceAppStatusResponse(v *ApplianceAppStatusList) ApplianceAppStatusResponse {
	return ApplianceAppStatusResponse{
		ApplianceAppStatusList: v,
	}
}

// MoAggregateTransformAsApplianceAppStatusResponse is a convenience function that returns MoAggregateTransform wrapped in ApplianceAppStatusResponse
func MoAggregateTransformAsApplianceAppStatusResponse(v *MoAggregateTransform) ApplianceAppStatusResponse {
	return ApplianceAppStatusResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsApplianceAppStatusResponse is a convenience function that returns MoDocumentCount wrapped in ApplianceAppStatusResponse
func MoDocumentCountAsApplianceAppStatusResponse(v *MoDocumentCount) ApplianceAppStatusResponse {
	return ApplianceAppStatusResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsApplianceAppStatusResponse is a convenience function that returns MoTagSummary wrapped in ApplianceAppStatusResponse
func MoTagSummaryAsApplianceAppStatusResponse(v *MoTagSummary) ApplianceAppStatusResponse {
	return ApplianceAppStatusResponse{
		MoTagSummary: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ApplianceAppStatusResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'appliance.AppStatus.List'
	if jsonDict["ObjectType"] == "appliance.AppStatus.List" {
		// try to unmarshal JSON data into ApplianceAppStatusList
		err = json.Unmarshal(data, &dst.ApplianceAppStatusList)
		if err == nil {
			return nil // data stored in dst.ApplianceAppStatusList, return on the first match
		} else {
			dst.ApplianceAppStatusList = nil
			return fmt.Errorf("failed to unmarshal ApplianceAppStatusResponse as ApplianceAppStatusList: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal ApplianceAppStatusResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal ApplianceAppStatusResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal ApplianceAppStatusResponse as MoTagSummary: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ApplianceAppStatusResponse) MarshalJSON() ([]byte, error) {
	if src.ApplianceAppStatusList != nil {
		return json.Marshal(&src.ApplianceAppStatusList)
	}

	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ApplianceAppStatusResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ApplianceAppStatusList != nil {
		return obj.ApplianceAppStatusList
	}

	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	// all schemas are nil
	return nil
}

type NullableApplianceAppStatusResponse struct {
	value *ApplianceAppStatusResponse
	isSet bool
}

func (v NullableApplianceAppStatusResponse) Get() *ApplianceAppStatusResponse {
	return v.value
}

func (v *NullableApplianceAppStatusResponse) Set(val *ApplianceAppStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApplianceAppStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApplianceAppStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplianceAppStatusResponse(val *ApplianceAppStatusResponse) *NullableApplianceAppStatusResponse {
	return &NullableApplianceAppStatusResponse{value: val, isSet: true}
}

func (v NullableApplianceAppStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplianceAppStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
