/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025092610
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// HciAhvVmNicRelationship - A relationship to the 'hci.AhvVmNic' resource, or the expanded 'hci.AhvVmNic' resource, or the 'null' value.
type HciAhvVmNicRelationship struct {
	HciAhvVmNic *HciAhvVmNic
	MoMoRef     *MoMoRef
}

// HciAhvVmNicAsHciAhvVmNicRelationship is a convenience function that returns HciAhvVmNic wrapped in HciAhvVmNicRelationship
func HciAhvVmNicAsHciAhvVmNicRelationship(v *HciAhvVmNic) HciAhvVmNicRelationship {
	return HciAhvVmNicRelationship{
		HciAhvVmNic: v,
	}
}

// MoMoRefAsHciAhvVmNicRelationship is a convenience function that returns MoMoRef wrapped in HciAhvVmNicRelationship
func MoMoRefAsHciAhvVmNicRelationship(v *MoMoRef) HciAhvVmNicRelationship {
	return HciAhvVmNicRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *HciAhvVmNicRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'hci.AhvVmNic'
	if jsonDict["ClassId"] == "hci.AhvVmNic" {
		// try to unmarshal JSON data into HciAhvVmNic
		err = json.Unmarshal(data, &dst.HciAhvVmNic)
		if err == nil {
			return nil // data stored in dst.HciAhvVmNic, return on the first match
		} else {
			dst.HciAhvVmNic = nil
			return fmt.Errorf("failed to unmarshal HciAhvVmNicRelationship as HciAhvVmNic: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal HciAhvVmNicRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src HciAhvVmNicRelationship) MarshalJSON() ([]byte, error) {
	if src.HciAhvVmNic != nil {
		return json.Marshal(&src.HciAhvVmNic)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *HciAhvVmNicRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.HciAhvVmNic != nil {
		return obj.HciAhvVmNic
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableHciAhvVmNicRelationship struct {
	value *HciAhvVmNicRelationship
	isSet bool
}

func (v NullableHciAhvVmNicRelationship) Get() *HciAhvVmNicRelationship {
	return v.value
}

func (v *NullableHciAhvVmNicRelationship) Set(val *HciAhvVmNicRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableHciAhvVmNicRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableHciAhvVmNicRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHciAhvVmNicRelationship(val *HciAhvVmNicRelationship) *NullableHciAhvVmNicRelationship {
	return &NullableHciAhvVmNicRelationship{value: val, isSet: true}
}

func (v NullableHciAhvVmNicRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHciAhvVmNicRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
