/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-15473
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// RecoveryScheduleConfigPolicyRelationship - A relationship to the 'recovery.ScheduleConfigPolicy' resource, or the expanded 'recovery.ScheduleConfigPolicy' resource, or the 'null' value.
type RecoveryScheduleConfigPolicyRelationship struct {
	MoMoRef                      *MoMoRef
	RecoveryScheduleConfigPolicy *RecoveryScheduleConfigPolicy
}

// MoMoRefAsRecoveryScheduleConfigPolicyRelationship is a convenience function that returns MoMoRef wrapped in RecoveryScheduleConfigPolicyRelationship
func MoMoRefAsRecoveryScheduleConfigPolicyRelationship(v *MoMoRef) RecoveryScheduleConfigPolicyRelationship {
	return RecoveryScheduleConfigPolicyRelationship{
		MoMoRef: v,
	}
}

// RecoveryScheduleConfigPolicyAsRecoveryScheduleConfigPolicyRelationship is a convenience function that returns RecoveryScheduleConfigPolicy wrapped in RecoveryScheduleConfigPolicyRelationship
func RecoveryScheduleConfigPolicyAsRecoveryScheduleConfigPolicyRelationship(v *RecoveryScheduleConfigPolicy) RecoveryScheduleConfigPolicyRelationship {
	return RecoveryScheduleConfigPolicyRelationship{
		RecoveryScheduleConfigPolicy: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *RecoveryScheduleConfigPolicyRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal RecoveryScheduleConfigPolicyRelationship as MoMoRef: %s", err.Error())
		}
	}

	// check if the discriminator value is 'recovery.ScheduleConfigPolicy'
	if jsonDict["ClassId"] == "recovery.ScheduleConfigPolicy" {
		// try to unmarshal JSON data into RecoveryScheduleConfigPolicy
		err = json.Unmarshal(data, &dst.RecoveryScheduleConfigPolicy)
		if err == nil {
			return nil // data stored in dst.RecoveryScheduleConfigPolicy, return on the first match
		} else {
			dst.RecoveryScheduleConfigPolicy = nil
			return fmt.Errorf("failed to unmarshal RecoveryScheduleConfigPolicyRelationship as RecoveryScheduleConfigPolicy: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RecoveryScheduleConfigPolicyRelationship) MarshalJSON() ([]byte, error) {
	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	if src.RecoveryScheduleConfigPolicy != nil {
		return json.Marshal(&src.RecoveryScheduleConfigPolicy)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RecoveryScheduleConfigPolicyRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	if obj.RecoveryScheduleConfigPolicy != nil {
		return obj.RecoveryScheduleConfigPolicy
	}

	// all schemas are nil
	return nil
}

type NullableRecoveryScheduleConfigPolicyRelationship struct {
	value *RecoveryScheduleConfigPolicyRelationship
	isSet bool
}

func (v NullableRecoveryScheduleConfigPolicyRelationship) Get() *RecoveryScheduleConfigPolicyRelationship {
	return v.value
}

func (v *NullableRecoveryScheduleConfigPolicyRelationship) Set(val *RecoveryScheduleConfigPolicyRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableRecoveryScheduleConfigPolicyRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableRecoveryScheduleConfigPolicyRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecoveryScheduleConfigPolicyRelationship(val *RecoveryScheduleConfigPolicyRelationship) *NullableRecoveryScheduleConfigPolicyRelationship {
	return &NullableRecoveryScheduleConfigPolicyRelationship{value: val, isSet: true}
}

func (v NullableRecoveryScheduleConfigPolicyRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecoveryScheduleConfigPolicyRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
