/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-18012
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// FcpoolReservationResponse - The response body of a HTTP GET request for the 'fcpool.Reservation' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'fcpool.Reservation' resources.
type FcpoolReservationResponse struct {
	FcpoolReservationList *FcpoolReservationList
	MoAggregateTransform  *MoAggregateTransform
	MoDocumentCount       *MoDocumentCount
	MoTagSummary          *MoTagSummary
}

// FcpoolReservationListAsFcpoolReservationResponse is a convenience function that returns FcpoolReservationList wrapped in FcpoolReservationResponse
func FcpoolReservationListAsFcpoolReservationResponse(v *FcpoolReservationList) FcpoolReservationResponse {
	return FcpoolReservationResponse{
		FcpoolReservationList: v,
	}
}

// MoAggregateTransformAsFcpoolReservationResponse is a convenience function that returns MoAggregateTransform wrapped in FcpoolReservationResponse
func MoAggregateTransformAsFcpoolReservationResponse(v *MoAggregateTransform) FcpoolReservationResponse {
	return FcpoolReservationResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsFcpoolReservationResponse is a convenience function that returns MoDocumentCount wrapped in FcpoolReservationResponse
func MoDocumentCountAsFcpoolReservationResponse(v *MoDocumentCount) FcpoolReservationResponse {
	return FcpoolReservationResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsFcpoolReservationResponse is a convenience function that returns MoTagSummary wrapped in FcpoolReservationResponse
func MoTagSummaryAsFcpoolReservationResponse(v *MoTagSummary) FcpoolReservationResponse {
	return FcpoolReservationResponse{
		MoTagSummary: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *FcpoolReservationResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'fcpool.Reservation.List'
	if jsonDict["ObjectType"] == "fcpool.Reservation.List" {
		// try to unmarshal JSON data into FcpoolReservationList
		err = json.Unmarshal(data, &dst.FcpoolReservationList)
		if err == nil {
			return nil // data stored in dst.FcpoolReservationList, return on the first match
		} else {
			dst.FcpoolReservationList = nil
			return fmt.Errorf("failed to unmarshal FcpoolReservationResponse as FcpoolReservationList: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal FcpoolReservationResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal FcpoolReservationResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal FcpoolReservationResponse as MoTagSummary: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FcpoolReservationResponse) MarshalJSON() ([]byte, error) {
	if src.FcpoolReservationList != nil {
		return json.Marshal(&src.FcpoolReservationList)
	}

	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FcpoolReservationResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FcpoolReservationList != nil {
		return obj.FcpoolReservationList
	}

	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	// all schemas are nil
	return nil
}

type NullableFcpoolReservationResponse struct {
	value *FcpoolReservationResponse
	isSet bool
}

func (v NullableFcpoolReservationResponse) Get() *FcpoolReservationResponse {
	return v.value
}

func (v *NullableFcpoolReservationResponse) Set(val *FcpoolReservationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFcpoolReservationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFcpoolReservationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFcpoolReservationResponse(val *FcpoolReservationResponse) *NullableFcpoolReservationResponse {
	return &NullableFcpoolReservationResponse{value: val, isSet: true}
}

func (v NullableFcpoolReservationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFcpoolReservationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
