/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-17057
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// FabricMulticastPolicyRelationship - A relationship to the 'fabric.MulticastPolicy' resource, or the expanded 'fabric.MulticastPolicy' resource, or the 'null' value.
type FabricMulticastPolicyRelationship struct {
	FabricMulticastPolicy *FabricMulticastPolicy
	MoMoRef               *MoMoRef
}

// FabricMulticastPolicyAsFabricMulticastPolicyRelationship is a convenience function that returns FabricMulticastPolicy wrapped in FabricMulticastPolicyRelationship
func FabricMulticastPolicyAsFabricMulticastPolicyRelationship(v *FabricMulticastPolicy) FabricMulticastPolicyRelationship {
	return FabricMulticastPolicyRelationship{
		FabricMulticastPolicy: v,
	}
}

// MoMoRefAsFabricMulticastPolicyRelationship is a convenience function that returns MoMoRef wrapped in FabricMulticastPolicyRelationship
func MoMoRefAsFabricMulticastPolicyRelationship(v *MoMoRef) FabricMulticastPolicyRelationship {
	return FabricMulticastPolicyRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *FabricMulticastPolicyRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'fabric.MulticastPolicy'
	if jsonDict["ClassId"] == "fabric.MulticastPolicy" {
		// try to unmarshal JSON data into FabricMulticastPolicy
		err = json.Unmarshal(data, &dst.FabricMulticastPolicy)
		if err == nil {
			return nil // data stored in dst.FabricMulticastPolicy, return on the first match
		} else {
			dst.FabricMulticastPolicy = nil
			return fmt.Errorf("failed to unmarshal FabricMulticastPolicyRelationship as FabricMulticastPolicy: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal FabricMulticastPolicyRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FabricMulticastPolicyRelationship) MarshalJSON() ([]byte, error) {
	if src.FabricMulticastPolicy != nil {
		return json.Marshal(&src.FabricMulticastPolicy)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FabricMulticastPolicyRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FabricMulticastPolicy != nil {
		return obj.FabricMulticastPolicy
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableFabricMulticastPolicyRelationship struct {
	value *FabricMulticastPolicyRelationship
	isSet bool
}

func (v NullableFabricMulticastPolicyRelationship) Get() *FabricMulticastPolicyRelationship {
	return v.value
}

func (v *NullableFabricMulticastPolicyRelationship) Set(val *FabricMulticastPolicyRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableFabricMulticastPolicyRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableFabricMulticastPolicyRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFabricMulticastPolicyRelationship(val *FabricMulticastPolicyRelationship) *NullableFabricMulticastPolicyRelationship {
	return &NullableFabricMulticastPolicyRelationship{value: val, isSet: true}
}

func (v NullableFabricMulticastPolicyRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFabricMulticastPolicyRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
