/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025101412
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// EquipmentFanModuleRelationship - A relationship to the 'equipment.FanModule' resource, or the expanded 'equipment.FanModule' resource, or the 'null' value.
type EquipmentFanModuleRelationship struct {
	EquipmentFanModule *EquipmentFanModule
	MoMoRef            *MoMoRef
}

// EquipmentFanModuleAsEquipmentFanModuleRelationship is a convenience function that returns EquipmentFanModule wrapped in EquipmentFanModuleRelationship
func EquipmentFanModuleAsEquipmentFanModuleRelationship(v *EquipmentFanModule) EquipmentFanModuleRelationship {
	return EquipmentFanModuleRelationship{
		EquipmentFanModule: v,
	}
}

// MoMoRefAsEquipmentFanModuleRelationship is a convenience function that returns MoMoRef wrapped in EquipmentFanModuleRelationship
func MoMoRefAsEquipmentFanModuleRelationship(v *MoMoRef) EquipmentFanModuleRelationship {
	return EquipmentFanModuleRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *EquipmentFanModuleRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'equipment.FanModule'
	if jsonDict["ClassId"] == "equipment.FanModule" {
		// try to unmarshal JSON data into EquipmentFanModule
		err = json.Unmarshal(data, &dst.EquipmentFanModule)
		if err == nil {
			return nil // data stored in dst.EquipmentFanModule, return on the first match
		} else {
			dst.EquipmentFanModule = nil
			return fmt.Errorf("failed to unmarshal EquipmentFanModuleRelationship as EquipmentFanModule: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal EquipmentFanModuleRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src EquipmentFanModuleRelationship) MarshalJSON() ([]byte, error) {
	if src.EquipmentFanModule != nil {
		return json.Marshal(&src.EquipmentFanModule)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *EquipmentFanModuleRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.EquipmentFanModule != nil {
		return obj.EquipmentFanModule
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableEquipmentFanModuleRelationship struct {
	value *EquipmentFanModuleRelationship
	isSet bool
}

func (v NullableEquipmentFanModuleRelationship) Get() *EquipmentFanModuleRelationship {
	return v.value
}

func (v *NullableEquipmentFanModuleRelationship) Set(val *EquipmentFanModuleRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableEquipmentFanModuleRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableEquipmentFanModuleRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEquipmentFanModuleRelationship(val *EquipmentFanModuleRelationship) *NullableEquipmentFanModuleRelationship {
	return &NullableEquipmentFanModuleRelationship{value: val, isSet: true}
}

func (v NullableEquipmentFanModuleRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEquipmentFanModuleRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
