/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-17412
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// MoBaseMoRelationship - A relationship to the 'mo.BaseMo' resource, or the expanded 'mo.BaseMo' resource, or the 'null' value.
type MoBaseMoRelationship struct {
	MoBaseMo *MoBaseMo
	MoMoRef  *MoMoRef
}

// MoBaseMoAsMoBaseMoRelationship is a convenience function that returns MoBaseMo wrapped in MoBaseMoRelationship
func MoBaseMoAsMoBaseMoRelationship(v *MoBaseMo) MoBaseMoRelationship {
	return MoBaseMoRelationship{
		MoBaseMo: v,
	}
}

// MoMoRefAsMoBaseMoRelationship is a convenience function that returns MoMoRef wrapped in MoBaseMoRelationship
func MoMoRefAsMoBaseMoRelationship(v *MoMoRef) MoBaseMoRelationship {
	return MoBaseMoRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *MoBaseMoRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.BaseMo'
	if jsonDict["ClassId"] == "mo.BaseMo" {
		// try to unmarshal JSON data into MoBaseMo
		err = json.Unmarshal(data, &dst.MoBaseMo)
		if err == nil {
			return nil // data stored in dst.MoBaseMo, return on the first match
		} else {
			dst.MoBaseMo = nil
			return fmt.Errorf("failed to unmarshal MoBaseMoRelationship as MoBaseMo: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal MoBaseMoRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MoBaseMoRelationship) MarshalJSON() ([]byte, error) {
	if src.MoBaseMo != nil {
		return json.Marshal(&src.MoBaseMo)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *MoBaseMoRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoBaseMo != nil {
		return obj.MoBaseMo
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableMoBaseMoRelationship struct {
	value *MoBaseMoRelationship
	isSet bool
}

func (v NullableMoBaseMoRelationship) Get() *MoBaseMoRelationship {
	return v.value
}

func (v *NullableMoBaseMoRelationship) Set(val *MoBaseMoRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableMoBaseMoRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableMoBaseMoRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoBaseMoRelationship(val *MoBaseMoRelationship) *NullableMoBaseMoRelationship {
	return &NullableMoBaseMoRelationship{value: val, isSet: true}
}

func (v NullableMoBaseMoRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoBaseMoRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
