/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-16711
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// VnicVnicTemplateResponse - The response body of a HTTP GET request for the 'vnic.VnicTemplate' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'vnic.VnicTemplate' resources.
type VnicVnicTemplateResponse struct {
	MoAggregateTransform *MoAggregateTransform
	MoDocumentCount      *MoDocumentCount
	MoTagSummary         *MoTagSummary
	VnicVnicTemplateList *VnicVnicTemplateList
}

// MoAggregateTransformAsVnicVnicTemplateResponse is a convenience function that returns MoAggregateTransform wrapped in VnicVnicTemplateResponse
func MoAggregateTransformAsVnicVnicTemplateResponse(v *MoAggregateTransform) VnicVnicTemplateResponse {
	return VnicVnicTemplateResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsVnicVnicTemplateResponse is a convenience function that returns MoDocumentCount wrapped in VnicVnicTemplateResponse
func MoDocumentCountAsVnicVnicTemplateResponse(v *MoDocumentCount) VnicVnicTemplateResponse {
	return VnicVnicTemplateResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsVnicVnicTemplateResponse is a convenience function that returns MoTagSummary wrapped in VnicVnicTemplateResponse
func MoTagSummaryAsVnicVnicTemplateResponse(v *MoTagSummary) VnicVnicTemplateResponse {
	return VnicVnicTemplateResponse{
		MoTagSummary: v,
	}
}

// VnicVnicTemplateListAsVnicVnicTemplateResponse is a convenience function that returns VnicVnicTemplateList wrapped in VnicVnicTemplateResponse
func VnicVnicTemplateListAsVnicVnicTemplateResponse(v *VnicVnicTemplateList) VnicVnicTemplateResponse {
	return VnicVnicTemplateResponse{
		VnicVnicTemplateList: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *VnicVnicTemplateResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal VnicVnicTemplateResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal VnicVnicTemplateResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal VnicVnicTemplateResponse as MoTagSummary: %s", err.Error())
		}
	}

	// check if the discriminator value is 'vnic.VnicTemplate.List'
	if jsonDict["ObjectType"] == "vnic.VnicTemplate.List" {
		// try to unmarshal JSON data into VnicVnicTemplateList
		err = json.Unmarshal(data, &dst.VnicVnicTemplateList)
		if err == nil {
			return nil // data stored in dst.VnicVnicTemplateList, return on the first match
		} else {
			dst.VnicVnicTemplateList = nil
			return fmt.Errorf("failed to unmarshal VnicVnicTemplateResponse as VnicVnicTemplateList: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VnicVnicTemplateResponse) MarshalJSON() ([]byte, error) {
	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	if src.VnicVnicTemplateList != nil {
		return json.Marshal(&src.VnicVnicTemplateList)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *VnicVnicTemplateResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	if obj.VnicVnicTemplateList != nil {
		return obj.VnicVnicTemplateList
	}

	// all schemas are nil
	return nil
}

type NullableVnicVnicTemplateResponse struct {
	value *VnicVnicTemplateResponse
	isSet bool
}

func (v NullableVnicVnicTemplateResponse) Get() *VnicVnicTemplateResponse {
	return v.value
}

func (v *NullableVnicVnicTemplateResponse) Set(val *VnicVnicTemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVnicVnicTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVnicVnicTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVnicVnicTemplateResponse(val *VnicVnicTemplateResponse) *NullableVnicVnicTemplateResponse {
	return &NullableVnicVnicTemplateResponse{value: val, isSet: true}
}

func (v NullableVnicVnicTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVnicVnicTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
