/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-18369
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the NiaapiApicLatestMaintainedRelease type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NiaapiApicLatestMaintainedRelease{}

// NiaapiApicLatestMaintainedRelease This contains the latest maintained release information for each release on APIC.
type NiaapiApicLatestMaintainedRelease struct {
	NiaapiMaintainedRelease
	AdditionalProperties map[string]interface{}
}

type _NiaapiApicLatestMaintainedRelease NiaapiApicLatestMaintainedRelease

// NewNiaapiApicLatestMaintainedRelease instantiates a new NiaapiApicLatestMaintainedRelease object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNiaapiApicLatestMaintainedRelease(classId string, objectType string) *NiaapiApicLatestMaintainedRelease {
	this := NiaapiApicLatestMaintainedRelease{}
	this.ClassId = classId
	this.ObjectType = objectType
	return &this
}

// NewNiaapiApicLatestMaintainedReleaseWithDefaults instantiates a new NiaapiApicLatestMaintainedRelease object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNiaapiApicLatestMaintainedReleaseWithDefaults() *NiaapiApicLatestMaintainedRelease {
	this := NiaapiApicLatestMaintainedRelease{}
	return &this
}

func (o NiaapiApicLatestMaintainedRelease) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NiaapiApicLatestMaintainedRelease) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedNiaapiMaintainedRelease, errNiaapiMaintainedRelease := json.Marshal(o.NiaapiMaintainedRelease)
	if errNiaapiMaintainedRelease != nil {
		return map[string]interface{}{}, errNiaapiMaintainedRelease
	}
	errNiaapiMaintainedRelease = json.Unmarshal([]byte(serializedNiaapiMaintainedRelease), &toSerialize)
	if errNiaapiMaintainedRelease != nil {
		return map[string]interface{}{}, errNiaapiMaintainedRelease
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NiaapiApicLatestMaintainedRelease) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ClassId",
		"ObjectType",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	type NiaapiApicLatestMaintainedReleaseWithoutEmbeddedStruct struct {
	}

	varNiaapiApicLatestMaintainedReleaseWithoutEmbeddedStruct := NiaapiApicLatestMaintainedReleaseWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varNiaapiApicLatestMaintainedReleaseWithoutEmbeddedStruct)
	if err == nil {
		varNiaapiApicLatestMaintainedRelease := _NiaapiApicLatestMaintainedRelease{}
		*o = NiaapiApicLatestMaintainedRelease(varNiaapiApicLatestMaintainedRelease)
	} else {
		return err
	}

	varNiaapiApicLatestMaintainedRelease := _NiaapiApicLatestMaintainedRelease{}

	err = json.Unmarshal(data, &varNiaapiApicLatestMaintainedRelease)
	if err == nil {
		o.NiaapiMaintainedRelease = varNiaapiApicLatestMaintainedRelease.NiaapiMaintainedRelease
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectNiaapiMaintainedRelease := reflect.ValueOf(o.NiaapiMaintainedRelease)
		for i := 0; i < reflectNiaapiMaintainedRelease.Type().NumField(); i++ {
			t := reflectNiaapiMaintainedRelease.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNiaapiApicLatestMaintainedRelease struct {
	value *NiaapiApicLatestMaintainedRelease
	isSet bool
}

func (v NullableNiaapiApicLatestMaintainedRelease) Get() *NiaapiApicLatestMaintainedRelease {
	return v.value
}

func (v *NullableNiaapiApicLatestMaintainedRelease) Set(val *NiaapiApicLatestMaintainedRelease) {
	v.value = val
	v.isSet = true
}

func (v NullableNiaapiApicLatestMaintainedRelease) IsSet() bool {
	return v.isSet
}

func (v *NullableNiaapiApicLatestMaintainedRelease) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNiaapiApicLatestMaintainedRelease(val *NiaapiApicLatestMaintainedRelease) *NullableNiaapiApicLatestMaintainedRelease {
	return &NullableNiaapiApicLatestMaintainedRelease{value: val, isSet: true}
}

func (v NullableNiaapiApicLatestMaintainedRelease) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNiaapiApicLatestMaintainedRelease) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
