/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025081401
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// FabricEthNetworkPolicyRelationship - A relationship to the 'fabric.EthNetworkPolicy' resource, or the expanded 'fabric.EthNetworkPolicy' resource, or the 'null' value.
type FabricEthNetworkPolicyRelationship struct {
	FabricEthNetworkPolicy *FabricEthNetworkPolicy
	MoMoRef                *MoMoRef
}

// FabricEthNetworkPolicyAsFabricEthNetworkPolicyRelationship is a convenience function that returns FabricEthNetworkPolicy wrapped in FabricEthNetworkPolicyRelationship
func FabricEthNetworkPolicyAsFabricEthNetworkPolicyRelationship(v *FabricEthNetworkPolicy) FabricEthNetworkPolicyRelationship {
	return FabricEthNetworkPolicyRelationship{
		FabricEthNetworkPolicy: v,
	}
}

// MoMoRefAsFabricEthNetworkPolicyRelationship is a convenience function that returns MoMoRef wrapped in FabricEthNetworkPolicyRelationship
func MoMoRefAsFabricEthNetworkPolicyRelationship(v *MoMoRef) FabricEthNetworkPolicyRelationship {
	return FabricEthNetworkPolicyRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *FabricEthNetworkPolicyRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'fabric.EthNetworkPolicy'
	if jsonDict["ClassId"] == "fabric.EthNetworkPolicy" {
		// try to unmarshal JSON data into FabricEthNetworkPolicy
		err = json.Unmarshal(data, &dst.FabricEthNetworkPolicy)
		if err == nil {
			return nil // data stored in dst.FabricEthNetworkPolicy, return on the first match
		} else {
			dst.FabricEthNetworkPolicy = nil
			return fmt.Errorf("failed to unmarshal FabricEthNetworkPolicyRelationship as FabricEthNetworkPolicy: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal FabricEthNetworkPolicyRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FabricEthNetworkPolicyRelationship) MarshalJSON() ([]byte, error) {
	if src.FabricEthNetworkPolicy != nil {
		return json.Marshal(&src.FabricEthNetworkPolicy)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FabricEthNetworkPolicyRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FabricEthNetworkPolicy != nil {
		return obj.FabricEthNetworkPolicy
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableFabricEthNetworkPolicyRelationship struct {
	value *FabricEthNetworkPolicyRelationship
	isSet bool
}

func (v NullableFabricEthNetworkPolicyRelationship) Get() *FabricEthNetworkPolicyRelationship {
	return v.value
}

func (v *NullableFabricEthNetworkPolicyRelationship) Set(val *FabricEthNetworkPolicyRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableFabricEthNetworkPolicyRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableFabricEthNetworkPolicyRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFabricEthNetworkPolicyRelationship(val *FabricEthNetworkPolicyRelationship) *NullableFabricEthNetworkPolicyRelationship {
	return &NullableFabricEthNetworkPolicyRelationship{value: val, isSet: true}
}

func (v NullableFabricEthNetworkPolicyRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFabricEthNetworkPolicyRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
