/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2024120409
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// FabricLinkControlPolicyRelationship - A relationship to the 'fabric.LinkControlPolicy' resource, or the expanded 'fabric.LinkControlPolicy' resource, or the 'null' value.
type FabricLinkControlPolicyRelationship struct {
	FabricLinkControlPolicy *FabricLinkControlPolicy
	MoMoRef                 *MoMoRef
}

// FabricLinkControlPolicyAsFabricLinkControlPolicyRelationship is a convenience function that returns FabricLinkControlPolicy wrapped in FabricLinkControlPolicyRelationship
func FabricLinkControlPolicyAsFabricLinkControlPolicyRelationship(v *FabricLinkControlPolicy) FabricLinkControlPolicyRelationship {
	return FabricLinkControlPolicyRelationship{
		FabricLinkControlPolicy: v,
	}
}

// MoMoRefAsFabricLinkControlPolicyRelationship is a convenience function that returns MoMoRef wrapped in FabricLinkControlPolicyRelationship
func MoMoRefAsFabricLinkControlPolicyRelationship(v *MoMoRef) FabricLinkControlPolicyRelationship {
	return FabricLinkControlPolicyRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *FabricLinkControlPolicyRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'fabric.LinkControlPolicy'
	if jsonDict["ClassId"] == "fabric.LinkControlPolicy" {
		// try to unmarshal JSON data into FabricLinkControlPolicy
		err = json.Unmarshal(data, &dst.FabricLinkControlPolicy)
		if err == nil {
			return nil // data stored in dst.FabricLinkControlPolicy, return on the first match
		} else {
			dst.FabricLinkControlPolicy = nil
			return fmt.Errorf("failed to unmarshal FabricLinkControlPolicyRelationship as FabricLinkControlPolicy: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal FabricLinkControlPolicyRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FabricLinkControlPolicyRelationship) MarshalJSON() ([]byte, error) {
	if src.FabricLinkControlPolicy != nil {
		return json.Marshal(&src.FabricLinkControlPolicy)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FabricLinkControlPolicyRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FabricLinkControlPolicy != nil {
		return obj.FabricLinkControlPolicy
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableFabricLinkControlPolicyRelationship struct {
	value *FabricLinkControlPolicyRelationship
	isSet bool
}

func (v NullableFabricLinkControlPolicyRelationship) Get() *FabricLinkControlPolicyRelationship {
	return v.value
}

func (v *NullableFabricLinkControlPolicyRelationship) Set(val *FabricLinkControlPolicyRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableFabricLinkControlPolicyRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableFabricLinkControlPolicyRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFabricLinkControlPolicyRelationship(val *FabricLinkControlPolicyRelationship) *NullableFabricLinkControlPolicyRelationship {
	return &NullableFabricLinkControlPolicyRelationship{value: val, isSet: true}
}

func (v NullableFabricLinkControlPolicyRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFabricLinkControlPolicyRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
