/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-18775
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// VnicEthNetworkPolicyInventoryRelationship - A relationship to the 'vnic.EthNetworkPolicyInventory' resource, or the expanded 'vnic.EthNetworkPolicyInventory' resource, or the 'null' value.
type VnicEthNetworkPolicyInventoryRelationship struct {
	MoMoRef                       *MoMoRef
	VnicEthNetworkPolicyInventory *VnicEthNetworkPolicyInventory
}

// MoMoRefAsVnicEthNetworkPolicyInventoryRelationship is a convenience function that returns MoMoRef wrapped in VnicEthNetworkPolicyInventoryRelationship
func MoMoRefAsVnicEthNetworkPolicyInventoryRelationship(v *MoMoRef) VnicEthNetworkPolicyInventoryRelationship {
	return VnicEthNetworkPolicyInventoryRelationship{
		MoMoRef: v,
	}
}

// VnicEthNetworkPolicyInventoryAsVnicEthNetworkPolicyInventoryRelationship is a convenience function that returns VnicEthNetworkPolicyInventory wrapped in VnicEthNetworkPolicyInventoryRelationship
func VnicEthNetworkPolicyInventoryAsVnicEthNetworkPolicyInventoryRelationship(v *VnicEthNetworkPolicyInventory) VnicEthNetworkPolicyInventoryRelationship {
	return VnicEthNetworkPolicyInventoryRelationship{
		VnicEthNetworkPolicyInventory: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *VnicEthNetworkPolicyInventoryRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal VnicEthNetworkPolicyInventoryRelationship as MoMoRef: %s", err.Error())
		}
	}

	// check if the discriminator value is 'vnic.EthNetworkPolicyInventory'
	if jsonDict["ClassId"] == "vnic.EthNetworkPolicyInventory" {
		// try to unmarshal JSON data into VnicEthNetworkPolicyInventory
		err = json.Unmarshal(data, &dst.VnicEthNetworkPolicyInventory)
		if err == nil {
			return nil // data stored in dst.VnicEthNetworkPolicyInventory, return on the first match
		} else {
			dst.VnicEthNetworkPolicyInventory = nil
			return fmt.Errorf("failed to unmarshal VnicEthNetworkPolicyInventoryRelationship as VnicEthNetworkPolicyInventory: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VnicEthNetworkPolicyInventoryRelationship) MarshalJSON() ([]byte, error) {
	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	if src.VnicEthNetworkPolicyInventory != nil {
		return json.Marshal(&src.VnicEthNetworkPolicyInventory)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *VnicEthNetworkPolicyInventoryRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	if obj.VnicEthNetworkPolicyInventory != nil {
		return obj.VnicEthNetworkPolicyInventory
	}

	// all schemas are nil
	return nil
}

type NullableVnicEthNetworkPolicyInventoryRelationship struct {
	value *VnicEthNetworkPolicyInventoryRelationship
	isSet bool
}

func (v NullableVnicEthNetworkPolicyInventoryRelationship) Get() *VnicEthNetworkPolicyInventoryRelationship {
	return v.value
}

func (v *NullableVnicEthNetworkPolicyInventoryRelationship) Set(val *VnicEthNetworkPolicyInventoryRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableVnicEthNetworkPolicyInventoryRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableVnicEthNetworkPolicyInventoryRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVnicEthNetworkPolicyInventoryRelationship(val *VnicEthNetworkPolicyInventoryRelationship) *NullableVnicEthNetworkPolicyInventoryRelationship {
	return &NullableVnicEthNetworkPolicyInventoryRelationship{value: val, isSet: true}
}

func (v NullableVnicEthNetworkPolicyInventoryRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVnicEthNetworkPolicyInventoryRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
