/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025062323
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// HyperflexLunRelationship - A relationship to the 'hyperflex.Lun' resource, or the expanded 'hyperflex.Lun' resource, or the 'null' value.
type HyperflexLunRelationship struct {
	HyperflexLun *HyperflexLun
	MoMoRef      *MoMoRef
}

// HyperflexLunAsHyperflexLunRelationship is a convenience function that returns HyperflexLun wrapped in HyperflexLunRelationship
func HyperflexLunAsHyperflexLunRelationship(v *HyperflexLun) HyperflexLunRelationship {
	return HyperflexLunRelationship{
		HyperflexLun: v,
	}
}

// MoMoRefAsHyperflexLunRelationship is a convenience function that returns MoMoRef wrapped in HyperflexLunRelationship
func MoMoRefAsHyperflexLunRelationship(v *MoMoRef) HyperflexLunRelationship {
	return HyperflexLunRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *HyperflexLunRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'hyperflex.Lun'
	if jsonDict["ClassId"] == "hyperflex.Lun" {
		// try to unmarshal JSON data into HyperflexLun
		err = json.Unmarshal(data, &dst.HyperflexLun)
		if err == nil {
			return nil // data stored in dst.HyperflexLun, return on the first match
		} else {
			dst.HyperflexLun = nil
			return fmt.Errorf("failed to unmarshal HyperflexLunRelationship as HyperflexLun: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal HyperflexLunRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src HyperflexLunRelationship) MarshalJSON() ([]byte, error) {
	if src.HyperflexLun != nil {
		return json.Marshal(&src.HyperflexLun)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *HyperflexLunRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.HyperflexLun != nil {
		return obj.HyperflexLun
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableHyperflexLunRelationship struct {
	value *HyperflexLunRelationship
	isSet bool
}

func (v NullableHyperflexLunRelationship) Get() *HyperflexLunRelationship {
	return v.value
}

func (v *NullableHyperflexLunRelationship) Set(val *HyperflexLunRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableHyperflexLunRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableHyperflexLunRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHyperflexLunRelationship(val *HyperflexLunRelationship) *NullableHyperflexLunRelationship {
	return &NullableHyperflexLunRelationship{value: val, isSet: true}
}

func (v NullableHyperflexLunRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHyperflexLunRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
