/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-18012
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the SchedulerRecurringScheduleParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchedulerRecurringScheduleParams{}

// SchedulerRecurringScheduleParams The parameters for configuring a recurring schedule.
type SchedulerRecurringScheduleParams struct {
	SchedulerBaseScheduleParams
	AdditionalProperties map[string]interface{}
}

type _SchedulerRecurringScheduleParams SchedulerRecurringScheduleParams

// NewSchedulerRecurringScheduleParams instantiates a new SchedulerRecurringScheduleParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchedulerRecurringScheduleParams(classId string, objectType string) *SchedulerRecurringScheduleParams {
	this := SchedulerRecurringScheduleParams{}
	this.ClassId = classId
	this.ObjectType = objectType
	var timeZone string = "Pacific/Niue"
	this.TimeZone = &timeZone
	return &this
}

// NewSchedulerRecurringScheduleParamsWithDefaults instantiates a new SchedulerRecurringScheduleParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchedulerRecurringScheduleParamsWithDefaults() *SchedulerRecurringScheduleParams {
	this := SchedulerRecurringScheduleParams{}
	return &this
}

func (o SchedulerRecurringScheduleParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchedulerRecurringScheduleParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedSchedulerBaseScheduleParams, errSchedulerBaseScheduleParams := json.Marshal(o.SchedulerBaseScheduleParams)
	if errSchedulerBaseScheduleParams != nil {
		return map[string]interface{}{}, errSchedulerBaseScheduleParams
	}
	errSchedulerBaseScheduleParams = json.Unmarshal([]byte(serializedSchedulerBaseScheduleParams), &toSerialize)
	if errSchedulerBaseScheduleParams != nil {
		return map[string]interface{}{}, errSchedulerBaseScheduleParams
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SchedulerRecurringScheduleParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ClassId",
		"ObjectType",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	type SchedulerRecurringScheduleParamsWithoutEmbeddedStruct struct {
	}

	varSchedulerRecurringScheduleParamsWithoutEmbeddedStruct := SchedulerRecurringScheduleParamsWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varSchedulerRecurringScheduleParamsWithoutEmbeddedStruct)
	if err == nil {
		varSchedulerRecurringScheduleParams := _SchedulerRecurringScheduleParams{}
		*o = SchedulerRecurringScheduleParams(varSchedulerRecurringScheduleParams)
	} else {
		return err
	}

	varSchedulerRecurringScheduleParams := _SchedulerRecurringScheduleParams{}

	err = json.Unmarshal(data, &varSchedulerRecurringScheduleParams)
	if err == nil {
		o.SchedulerBaseScheduleParams = varSchedulerRecurringScheduleParams.SchedulerBaseScheduleParams
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectSchedulerBaseScheduleParams := reflect.ValueOf(o.SchedulerBaseScheduleParams)
		for i := 0; i < reflectSchedulerBaseScheduleParams.Type().NumField(); i++ {
			t := reflectSchedulerBaseScheduleParams.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSchedulerRecurringScheduleParams struct {
	value *SchedulerRecurringScheduleParams
	isSet bool
}

func (v NullableSchedulerRecurringScheduleParams) Get() *SchedulerRecurringScheduleParams {
	return v.value
}

func (v *NullableSchedulerRecurringScheduleParams) Set(val *SchedulerRecurringScheduleParams) {
	v.value = val
	v.isSet = true
}

func (v NullableSchedulerRecurringScheduleParams) IsSet() bool {
	return v.isSet
}

func (v *NullableSchedulerRecurringScheduleParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchedulerRecurringScheduleParams(val *SchedulerRecurringScheduleParams) *NullableSchedulerRecurringScheduleParams {
	return &NullableSchedulerRecurringScheduleParams{value: val, isSet: true}
}

func (v NullableSchedulerRecurringScheduleParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchedulerRecurringScheduleParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
