/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-15473
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// HyperflexServerFirmwareVersionResponse - The response body of a HTTP GET request for the 'hyperflex.ServerFirmwareVersion' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'hyperflex.ServerFirmwareVersion' resources.
type HyperflexServerFirmwareVersionResponse struct {
	HyperflexServerFirmwareVersionList *HyperflexServerFirmwareVersionList
	MoAggregateTransform               *MoAggregateTransform
	MoDocumentCount                    *MoDocumentCount
	MoTagSummary                       *MoTagSummary
}

// HyperflexServerFirmwareVersionListAsHyperflexServerFirmwareVersionResponse is a convenience function that returns HyperflexServerFirmwareVersionList wrapped in HyperflexServerFirmwareVersionResponse
func HyperflexServerFirmwareVersionListAsHyperflexServerFirmwareVersionResponse(v *HyperflexServerFirmwareVersionList) HyperflexServerFirmwareVersionResponse {
	return HyperflexServerFirmwareVersionResponse{
		HyperflexServerFirmwareVersionList: v,
	}
}

// MoAggregateTransformAsHyperflexServerFirmwareVersionResponse is a convenience function that returns MoAggregateTransform wrapped in HyperflexServerFirmwareVersionResponse
func MoAggregateTransformAsHyperflexServerFirmwareVersionResponse(v *MoAggregateTransform) HyperflexServerFirmwareVersionResponse {
	return HyperflexServerFirmwareVersionResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsHyperflexServerFirmwareVersionResponse is a convenience function that returns MoDocumentCount wrapped in HyperflexServerFirmwareVersionResponse
func MoDocumentCountAsHyperflexServerFirmwareVersionResponse(v *MoDocumentCount) HyperflexServerFirmwareVersionResponse {
	return HyperflexServerFirmwareVersionResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsHyperflexServerFirmwareVersionResponse is a convenience function that returns MoTagSummary wrapped in HyperflexServerFirmwareVersionResponse
func MoTagSummaryAsHyperflexServerFirmwareVersionResponse(v *MoTagSummary) HyperflexServerFirmwareVersionResponse {
	return HyperflexServerFirmwareVersionResponse{
		MoTagSummary: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *HyperflexServerFirmwareVersionResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'hyperflex.ServerFirmwareVersion.List'
	if jsonDict["ObjectType"] == "hyperflex.ServerFirmwareVersion.List" {
		// try to unmarshal JSON data into HyperflexServerFirmwareVersionList
		err = json.Unmarshal(data, &dst.HyperflexServerFirmwareVersionList)
		if err == nil {
			return nil // data stored in dst.HyperflexServerFirmwareVersionList, return on the first match
		} else {
			dst.HyperflexServerFirmwareVersionList = nil
			return fmt.Errorf("failed to unmarshal HyperflexServerFirmwareVersionResponse as HyperflexServerFirmwareVersionList: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal HyperflexServerFirmwareVersionResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal HyperflexServerFirmwareVersionResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal HyperflexServerFirmwareVersionResponse as MoTagSummary: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src HyperflexServerFirmwareVersionResponse) MarshalJSON() ([]byte, error) {
	if src.HyperflexServerFirmwareVersionList != nil {
		return json.Marshal(&src.HyperflexServerFirmwareVersionList)
	}

	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *HyperflexServerFirmwareVersionResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.HyperflexServerFirmwareVersionList != nil {
		return obj.HyperflexServerFirmwareVersionList
	}

	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	// all schemas are nil
	return nil
}

type NullableHyperflexServerFirmwareVersionResponse struct {
	value *HyperflexServerFirmwareVersionResponse
	isSet bool
}

func (v NullableHyperflexServerFirmwareVersionResponse) Get() *HyperflexServerFirmwareVersionResponse {
	return v.value
}

func (v *NullableHyperflexServerFirmwareVersionResponse) Set(val *HyperflexServerFirmwareVersionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHyperflexServerFirmwareVersionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHyperflexServerFirmwareVersionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHyperflexServerFirmwareVersionResponse(val *HyperflexServerFirmwareVersionResponse) *NullableHyperflexServerFirmwareVersionResponse {
	return &NullableHyperflexServerFirmwareVersionResponse{value: val, isSet: true}
}

func (v NullableHyperflexServerFirmwareVersionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHyperflexServerFirmwareVersionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
