/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-16711
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// IqnpoolLeaseRelationship - A relationship to the 'iqnpool.Lease' resource, or the expanded 'iqnpool.Lease' resource, or the 'null' value.
type IqnpoolLeaseRelationship struct {
	IqnpoolLease *IqnpoolLease
	MoMoRef      *MoMoRef
}

// IqnpoolLeaseAsIqnpoolLeaseRelationship is a convenience function that returns IqnpoolLease wrapped in IqnpoolLeaseRelationship
func IqnpoolLeaseAsIqnpoolLeaseRelationship(v *IqnpoolLease) IqnpoolLeaseRelationship {
	return IqnpoolLeaseRelationship{
		IqnpoolLease: v,
	}
}

// MoMoRefAsIqnpoolLeaseRelationship is a convenience function that returns MoMoRef wrapped in IqnpoolLeaseRelationship
func MoMoRefAsIqnpoolLeaseRelationship(v *MoMoRef) IqnpoolLeaseRelationship {
	return IqnpoolLeaseRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *IqnpoolLeaseRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'iqnpool.Lease'
	if jsonDict["ClassId"] == "iqnpool.Lease" {
		// try to unmarshal JSON data into IqnpoolLease
		err = json.Unmarshal(data, &dst.IqnpoolLease)
		if err == nil {
			return nil // data stored in dst.IqnpoolLease, return on the first match
		} else {
			dst.IqnpoolLease = nil
			return fmt.Errorf("failed to unmarshal IqnpoolLeaseRelationship as IqnpoolLease: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal IqnpoolLeaseRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src IqnpoolLeaseRelationship) MarshalJSON() ([]byte, error) {
	if src.IqnpoolLease != nil {
		return json.Marshal(&src.IqnpoolLease)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *IqnpoolLeaseRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.IqnpoolLease != nil {
		return obj.IqnpoolLease
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableIqnpoolLeaseRelationship struct {
	value *IqnpoolLeaseRelationship
	isSet bool
}

func (v NullableIqnpoolLeaseRelationship) Get() *IqnpoolLeaseRelationship {
	return v.value
}

func (v *NullableIqnpoolLeaseRelationship) Set(val *IqnpoolLeaseRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableIqnpoolLeaseRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableIqnpoolLeaseRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIqnpoolLeaseRelationship(val *IqnpoolLeaseRelationship) *NullableIqnpoolLeaseRelationship {
	return &NullableIqnpoolLeaseRelationship{value: val, isSet: true}
}

func (v NullableIqnpoolLeaseRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIqnpoolLeaseRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
