/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2024112619
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the InfraGpuConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InfraGpuConfiguration{}

// InfraGpuConfiguration Generic GPU configuration on a compute resource (BM or VM).
type InfraGpuConfiguration struct {
	InfraBaseGpuConfiguration
	AdditionalProperties map[string]interface{}
}

type _InfraGpuConfiguration InfraGpuConfiguration

// NewInfraGpuConfiguration instantiates a new InfraGpuConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfraGpuConfiguration(classId string, objectType string) *InfraGpuConfiguration {
	this := InfraGpuConfiguration{}
	this.ClassId = classId
	this.ObjectType = objectType
	return &this
}

// NewInfraGpuConfigurationWithDefaults instantiates a new InfraGpuConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfraGpuConfigurationWithDefaults() *InfraGpuConfiguration {
	this := InfraGpuConfiguration{}
	return &this
}

func (o InfraGpuConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InfraGpuConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedInfraBaseGpuConfiguration, errInfraBaseGpuConfiguration := json.Marshal(o.InfraBaseGpuConfiguration)
	if errInfraBaseGpuConfiguration != nil {
		return map[string]interface{}{}, errInfraBaseGpuConfiguration
	}
	errInfraBaseGpuConfiguration = json.Unmarshal([]byte(serializedInfraBaseGpuConfiguration), &toSerialize)
	if errInfraBaseGpuConfiguration != nil {
		return map[string]interface{}{}, errInfraBaseGpuConfiguration
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InfraGpuConfiguration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ClassId",
		"ObjectType",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	type InfraGpuConfigurationWithoutEmbeddedStruct struct {
	}

	varInfraGpuConfigurationWithoutEmbeddedStruct := InfraGpuConfigurationWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varInfraGpuConfigurationWithoutEmbeddedStruct)
	if err == nil {
		varInfraGpuConfiguration := _InfraGpuConfiguration{}
		*o = InfraGpuConfiguration(varInfraGpuConfiguration)
	} else {
		return err
	}

	varInfraGpuConfiguration := _InfraGpuConfiguration{}

	err = json.Unmarshal(data, &varInfraGpuConfiguration)
	if err == nil {
		o.InfraBaseGpuConfiguration = varInfraGpuConfiguration.InfraBaseGpuConfiguration
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectInfraBaseGpuConfiguration := reflect.ValueOf(o.InfraBaseGpuConfiguration)
		for i := 0; i < reflectInfraBaseGpuConfiguration.Type().NumField(); i++ {
			t := reflectInfraBaseGpuConfiguration.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInfraGpuConfiguration struct {
	value *InfraGpuConfiguration
	isSet bool
}

func (v NullableInfraGpuConfiguration) Get() *InfraGpuConfiguration {
	return v.value
}

func (v *NullableInfraGpuConfiguration) Set(val *InfraGpuConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableInfraGpuConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableInfraGpuConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfraGpuConfiguration(val *InfraGpuConfiguration) *NullableInfraGpuConfiguration {
	return &NullableInfraGpuConfiguration{value: val, isSet: true}
}

func (v NullableInfraGpuConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfraGpuConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
