/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-17057
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the FirmwareDriveDescriptor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FirmwareDriveDescriptor{}

// FirmwareDriveDescriptor Descriptor to uniquely identify a Drive.
type FirmwareDriveDescriptor struct {
	FirmwareComponentDescriptor
	AdditionalProperties map[string]interface{}
}

type _FirmwareDriveDescriptor FirmwareDriveDescriptor

// NewFirmwareDriveDescriptor instantiates a new FirmwareDriveDescriptor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirmwareDriveDescriptor(classId string, objectType string) *FirmwareDriveDescriptor {
	this := FirmwareDriveDescriptor{}
	this.ClassId = classId
	this.ObjectType = objectType
	return &this
}

// NewFirmwareDriveDescriptorWithDefaults instantiates a new FirmwareDriveDescriptor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirmwareDriveDescriptorWithDefaults() *FirmwareDriveDescriptor {
	this := FirmwareDriveDescriptor{}
	return &this
}

func (o FirmwareDriveDescriptor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FirmwareDriveDescriptor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedFirmwareComponentDescriptor, errFirmwareComponentDescriptor := json.Marshal(o.FirmwareComponentDescriptor)
	if errFirmwareComponentDescriptor != nil {
		return map[string]interface{}{}, errFirmwareComponentDescriptor
	}
	errFirmwareComponentDescriptor = json.Unmarshal([]byte(serializedFirmwareComponentDescriptor), &toSerialize)
	if errFirmwareComponentDescriptor != nil {
		return map[string]interface{}{}, errFirmwareComponentDescriptor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FirmwareDriveDescriptor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ClassId",
		"ObjectType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	type FirmwareDriveDescriptorWithoutEmbeddedStruct struct {
	}

	varFirmwareDriveDescriptorWithoutEmbeddedStruct := FirmwareDriveDescriptorWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varFirmwareDriveDescriptorWithoutEmbeddedStruct)
	if err == nil {
		varFirmwareDriveDescriptor := _FirmwareDriveDescriptor{}
		*o = FirmwareDriveDescriptor(varFirmwareDriveDescriptor)
	} else {
		return err
	}

	varFirmwareDriveDescriptor := _FirmwareDriveDescriptor{}

	err = json.Unmarshal(data, &varFirmwareDriveDescriptor)
	if err == nil {
		o.FirmwareComponentDescriptor = varFirmwareDriveDescriptor.FirmwareComponentDescriptor
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectFirmwareComponentDescriptor := reflect.ValueOf(o.FirmwareComponentDescriptor)
		for i := 0; i < reflectFirmwareComponentDescriptor.Type().NumField(); i++ {
			t := reflectFirmwareComponentDescriptor.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFirmwareDriveDescriptor struct {
	value *FirmwareDriveDescriptor
	isSet bool
}

func (v NullableFirmwareDriveDescriptor) Get() *FirmwareDriveDescriptor {
	return v.value
}

func (v *NullableFirmwareDriveDescriptor) Set(val *FirmwareDriveDescriptor) {
	v.value = val
	v.isSet = true
}

func (v NullableFirmwareDriveDescriptor) IsSet() bool {
	return v.isSet
}

func (v *NullableFirmwareDriveDescriptor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirmwareDriveDescriptor(val *FirmwareDriveDescriptor) *NullableFirmwareDriveDescriptor {
	return &NullableFirmwareDriveDescriptor{value: val, isSet: true}
}

func (v NullableFirmwareDriveDescriptor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirmwareDriveDescriptor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
