/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-17227
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// InventoryDeviceInfoRelationship - A relationship to the 'inventory.DeviceInfo' resource, or the expanded 'inventory.DeviceInfo' resource, or the 'null' value.
type InventoryDeviceInfoRelationship struct {
	InventoryDeviceInfo *InventoryDeviceInfo
	MoMoRef             *MoMoRef
}

// InventoryDeviceInfoAsInventoryDeviceInfoRelationship is a convenience function that returns InventoryDeviceInfo wrapped in InventoryDeviceInfoRelationship
func InventoryDeviceInfoAsInventoryDeviceInfoRelationship(v *InventoryDeviceInfo) InventoryDeviceInfoRelationship {
	return InventoryDeviceInfoRelationship{
		InventoryDeviceInfo: v,
	}
}

// MoMoRefAsInventoryDeviceInfoRelationship is a convenience function that returns MoMoRef wrapped in InventoryDeviceInfoRelationship
func MoMoRefAsInventoryDeviceInfoRelationship(v *MoMoRef) InventoryDeviceInfoRelationship {
	return InventoryDeviceInfoRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *InventoryDeviceInfoRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'inventory.DeviceInfo'
	if jsonDict["ClassId"] == "inventory.DeviceInfo" {
		// try to unmarshal JSON data into InventoryDeviceInfo
		err = json.Unmarshal(data, &dst.InventoryDeviceInfo)
		if err == nil {
			return nil // data stored in dst.InventoryDeviceInfo, return on the first match
		} else {
			dst.InventoryDeviceInfo = nil
			return fmt.Errorf("failed to unmarshal InventoryDeviceInfoRelationship as InventoryDeviceInfo: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal InventoryDeviceInfoRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InventoryDeviceInfoRelationship) MarshalJSON() ([]byte, error) {
	if src.InventoryDeviceInfo != nil {
		return json.Marshal(&src.InventoryDeviceInfo)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *InventoryDeviceInfoRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.InventoryDeviceInfo != nil {
		return obj.InventoryDeviceInfo
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableInventoryDeviceInfoRelationship struct {
	value *InventoryDeviceInfoRelationship
	isSet bool
}

func (v NullableInventoryDeviceInfoRelationship) Get() *InventoryDeviceInfoRelationship {
	return v.value
}

func (v *NullableInventoryDeviceInfoRelationship) Set(val *InventoryDeviceInfoRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryDeviceInfoRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryDeviceInfoRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryDeviceInfoRelationship(val *InventoryDeviceInfoRelationship) *NullableInventoryDeviceInfoRelationship {
	return &NullableInventoryDeviceInfoRelationship{value: val, isSet: true}
}

func (v NullableInventoryDeviceInfoRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryDeviceInfoRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
