/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025102807
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// PolicyAbstractPolicyRelationship - A relationship to the 'policy.AbstractPolicy' resource, or the expanded 'policy.AbstractPolicy' resource, or the 'null' value.
type PolicyAbstractPolicyRelationship struct {
	MoMoRef              *MoMoRef
	PolicyAbstractPolicy *PolicyAbstractPolicy
}

// MoMoRefAsPolicyAbstractPolicyRelationship is a convenience function that returns MoMoRef wrapped in PolicyAbstractPolicyRelationship
func MoMoRefAsPolicyAbstractPolicyRelationship(v *MoMoRef) PolicyAbstractPolicyRelationship {
	return PolicyAbstractPolicyRelationship{
		MoMoRef: v,
	}
}

// PolicyAbstractPolicyAsPolicyAbstractPolicyRelationship is a convenience function that returns PolicyAbstractPolicy wrapped in PolicyAbstractPolicyRelationship
func PolicyAbstractPolicyAsPolicyAbstractPolicyRelationship(v *PolicyAbstractPolicy) PolicyAbstractPolicyRelationship {
	return PolicyAbstractPolicyRelationship{
		PolicyAbstractPolicy: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PolicyAbstractPolicyRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal PolicyAbstractPolicyRelationship as MoMoRef: %s", err.Error())
		}
	}

	// check if the discriminator value is 'policy.AbstractPolicy'
	if jsonDict["ClassId"] == "policy.AbstractPolicy" {
		// try to unmarshal JSON data into PolicyAbstractPolicy
		err = json.Unmarshal(data, &dst.PolicyAbstractPolicy)
		if err == nil {
			return nil // data stored in dst.PolicyAbstractPolicy, return on the first match
		} else {
			dst.PolicyAbstractPolicy = nil
			return fmt.Errorf("failed to unmarshal PolicyAbstractPolicyRelationship as PolicyAbstractPolicy: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PolicyAbstractPolicyRelationship) MarshalJSON() ([]byte, error) {
	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	if src.PolicyAbstractPolicy != nil {
		return json.Marshal(&src.PolicyAbstractPolicy)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PolicyAbstractPolicyRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	if obj.PolicyAbstractPolicy != nil {
		return obj.PolicyAbstractPolicy
	}

	// all schemas are nil
	return nil
}

type NullablePolicyAbstractPolicyRelationship struct {
	value *PolicyAbstractPolicyRelationship
	isSet bool
}

func (v NullablePolicyAbstractPolicyRelationship) Get() *PolicyAbstractPolicyRelationship {
	return v.value
}

func (v *NullablePolicyAbstractPolicyRelationship) Set(val *PolicyAbstractPolicyRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyAbstractPolicyRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyAbstractPolicyRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyAbstractPolicyRelationship(val *PolicyAbstractPolicyRelationship) *NullablePolicyAbstractPolicyRelationship {
	return &NullablePolicyAbstractPolicyRelationship{value: val, isSet: true}
}

func (v NullablePolicyAbstractPolicyRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyAbstractPolicyRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
