/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-18369
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the AssetDeviceEndpointLocalCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetDeviceEndpointLocalCredential{}

// AssetDeviceEndpointLocalCredential Used against a device endpoint that manages its own local credential.
type AssetDeviceEndpointLocalCredential struct {
	AssetCredential
	AdditionalProperties map[string]interface{}
}

type _AssetDeviceEndpointLocalCredential AssetDeviceEndpointLocalCredential

// NewAssetDeviceEndpointLocalCredential instantiates a new AssetDeviceEndpointLocalCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetDeviceEndpointLocalCredential(classId string, objectType string) *AssetDeviceEndpointLocalCredential {
	this := AssetDeviceEndpointLocalCredential{}
	this.ClassId = classId
	this.ObjectType = objectType
	return &this
}

// NewAssetDeviceEndpointLocalCredentialWithDefaults instantiates a new AssetDeviceEndpointLocalCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetDeviceEndpointLocalCredentialWithDefaults() *AssetDeviceEndpointLocalCredential {
	this := AssetDeviceEndpointLocalCredential{}
	return &this
}

func (o AssetDeviceEndpointLocalCredential) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetDeviceEndpointLocalCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedAssetCredential, errAssetCredential := json.Marshal(o.AssetCredential)
	if errAssetCredential != nil {
		return map[string]interface{}{}, errAssetCredential
	}
	errAssetCredential = json.Unmarshal([]byte(serializedAssetCredential), &toSerialize)
	if errAssetCredential != nil {
		return map[string]interface{}{}, errAssetCredential
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AssetDeviceEndpointLocalCredential) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ClassId",
		"ObjectType",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	type AssetDeviceEndpointLocalCredentialWithoutEmbeddedStruct struct {
	}

	varAssetDeviceEndpointLocalCredentialWithoutEmbeddedStruct := AssetDeviceEndpointLocalCredentialWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varAssetDeviceEndpointLocalCredentialWithoutEmbeddedStruct)
	if err == nil {
		varAssetDeviceEndpointLocalCredential := _AssetDeviceEndpointLocalCredential{}
		*o = AssetDeviceEndpointLocalCredential(varAssetDeviceEndpointLocalCredential)
	} else {
		return err
	}

	varAssetDeviceEndpointLocalCredential := _AssetDeviceEndpointLocalCredential{}

	err = json.Unmarshal(data, &varAssetDeviceEndpointLocalCredential)
	if err == nil {
		o.AssetCredential = varAssetDeviceEndpointLocalCredential.AssetCredential
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {

		// remove fields from embedded structs
		reflectAssetCredential := reflect.ValueOf(o.AssetCredential)
		for i := 0; i < reflectAssetCredential.Type().NumField(); i++ {
			t := reflectAssetCredential.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAssetDeviceEndpointLocalCredential struct {
	value *AssetDeviceEndpointLocalCredential
	isSet bool
}

func (v NullableAssetDeviceEndpointLocalCredential) Get() *AssetDeviceEndpointLocalCredential {
	return v.value
}

func (v *NullableAssetDeviceEndpointLocalCredential) Set(val *AssetDeviceEndpointLocalCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetDeviceEndpointLocalCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetDeviceEndpointLocalCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetDeviceEndpointLocalCredential(val *AssetDeviceEndpointLocalCredential) *NullableAssetDeviceEndpointLocalCredential {
	return &NullableAssetDeviceEndpointLocalCredential{value: val, isSet: true}
}

func (v NullableAssetDeviceEndpointLocalCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetDeviceEndpointLocalCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
