/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025081401
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// NetworkFeatureControlRelationship - A relationship to the 'network.FeatureControl' resource, or the expanded 'network.FeatureControl' resource, or the 'null' value.
type NetworkFeatureControlRelationship struct {
	MoMoRef               *MoMoRef
	NetworkFeatureControl *NetworkFeatureControl
}

// MoMoRefAsNetworkFeatureControlRelationship is a convenience function that returns MoMoRef wrapped in NetworkFeatureControlRelationship
func MoMoRefAsNetworkFeatureControlRelationship(v *MoMoRef) NetworkFeatureControlRelationship {
	return NetworkFeatureControlRelationship{
		MoMoRef: v,
	}
}

// NetworkFeatureControlAsNetworkFeatureControlRelationship is a convenience function that returns NetworkFeatureControl wrapped in NetworkFeatureControlRelationship
func NetworkFeatureControlAsNetworkFeatureControlRelationship(v *NetworkFeatureControl) NetworkFeatureControlRelationship {
	return NetworkFeatureControlRelationship{
		NetworkFeatureControl: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *NetworkFeatureControlRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal NetworkFeatureControlRelationship as MoMoRef: %s", err.Error())
		}
	}

	// check if the discriminator value is 'network.FeatureControl'
	if jsonDict["ClassId"] == "network.FeatureControl" {
		// try to unmarshal JSON data into NetworkFeatureControl
		err = json.Unmarshal(data, &dst.NetworkFeatureControl)
		if err == nil {
			return nil // data stored in dst.NetworkFeatureControl, return on the first match
		} else {
			dst.NetworkFeatureControl = nil
			return fmt.Errorf("failed to unmarshal NetworkFeatureControlRelationship as NetworkFeatureControl: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src NetworkFeatureControlRelationship) MarshalJSON() ([]byte, error) {
	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	if src.NetworkFeatureControl != nil {
		return json.Marshal(&src.NetworkFeatureControl)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *NetworkFeatureControlRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	if obj.NetworkFeatureControl != nil {
		return obj.NetworkFeatureControl
	}

	// all schemas are nil
	return nil
}

type NullableNetworkFeatureControlRelationship struct {
	value *NetworkFeatureControlRelationship
	isSet bool
}

func (v NullableNetworkFeatureControlRelationship) Get() *NetworkFeatureControlRelationship {
	return v.value
}

func (v *NullableNetworkFeatureControlRelationship) Set(val *NetworkFeatureControlRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkFeatureControlRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkFeatureControlRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkFeatureControlRelationship(val *NetworkFeatureControlRelationship) *NullableNetworkFeatureControlRelationship {
	return &NullableNetworkFeatureControlRelationship{value: val, isSet: true}
}

func (v NullableNetworkFeatureControlRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkFeatureControlRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
