/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-14968
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// PciSwitchRelationship - A relationship to the 'pci.Switch' resource, or the expanded 'pci.Switch' resource, or the 'null' value.
type PciSwitchRelationship struct {
	MoMoRef   *MoMoRef
	PciSwitch *PciSwitch
}

// MoMoRefAsPciSwitchRelationship is a convenience function that returns MoMoRef wrapped in PciSwitchRelationship
func MoMoRefAsPciSwitchRelationship(v *MoMoRef) PciSwitchRelationship {
	return PciSwitchRelationship{
		MoMoRef: v,
	}
}

// PciSwitchAsPciSwitchRelationship is a convenience function that returns PciSwitch wrapped in PciSwitchRelationship
func PciSwitchAsPciSwitchRelationship(v *PciSwitch) PciSwitchRelationship {
	return PciSwitchRelationship{
		PciSwitch: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PciSwitchRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal PciSwitchRelationship as MoMoRef: %s", err.Error())
		}
	}

	// check if the discriminator value is 'pci.Switch'
	if jsonDict["ClassId"] == "pci.Switch" {
		// try to unmarshal JSON data into PciSwitch
		err = json.Unmarshal(data, &dst.PciSwitch)
		if err == nil {
			return nil // data stored in dst.PciSwitch, return on the first match
		} else {
			dst.PciSwitch = nil
			return fmt.Errorf("failed to unmarshal PciSwitchRelationship as PciSwitch: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PciSwitchRelationship) MarshalJSON() ([]byte, error) {
	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	if src.PciSwitch != nil {
		return json.Marshal(&src.PciSwitch)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PciSwitchRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	if obj.PciSwitch != nil {
		return obj.PciSwitch
	}

	// all schemas are nil
	return nil
}

type NullablePciSwitchRelationship struct {
	value *PciSwitchRelationship
	isSet bool
}

func (v NullablePciSwitchRelationship) Get() *PciSwitchRelationship {
	return v.value
}

func (v *NullablePciSwitchRelationship) Set(val *PciSwitchRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullablePciSwitchRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullablePciSwitchRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePciSwitchRelationship(val *PciSwitchRelationship) *NullablePciSwitchRelationship {
	return &NullablePciSwitchRelationship{value: val, isSet: true}
}

func (v NullablePciSwitchRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePciSwitchRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
