/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-18369
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// ApplianceSystemOpStatusRelationship - A relationship to the 'appliance.SystemOpStatus' resource, or the expanded 'appliance.SystemOpStatus' resource, or the 'null' value.
type ApplianceSystemOpStatusRelationship struct {
	ApplianceSystemOpStatus *ApplianceSystemOpStatus
	MoMoRef                 *MoMoRef
}

// ApplianceSystemOpStatusAsApplianceSystemOpStatusRelationship is a convenience function that returns ApplianceSystemOpStatus wrapped in ApplianceSystemOpStatusRelationship
func ApplianceSystemOpStatusAsApplianceSystemOpStatusRelationship(v *ApplianceSystemOpStatus) ApplianceSystemOpStatusRelationship {
	return ApplianceSystemOpStatusRelationship{
		ApplianceSystemOpStatus: v,
	}
}

// MoMoRefAsApplianceSystemOpStatusRelationship is a convenience function that returns MoMoRef wrapped in ApplianceSystemOpStatusRelationship
func MoMoRefAsApplianceSystemOpStatusRelationship(v *MoMoRef) ApplianceSystemOpStatusRelationship {
	return ApplianceSystemOpStatusRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ApplianceSystemOpStatusRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'appliance.SystemOpStatus'
	if jsonDict["ClassId"] == "appliance.SystemOpStatus" {
		// try to unmarshal JSON data into ApplianceSystemOpStatus
		err = json.Unmarshal(data, &dst.ApplianceSystemOpStatus)
		if err == nil {
			return nil // data stored in dst.ApplianceSystemOpStatus, return on the first match
		} else {
			dst.ApplianceSystemOpStatus = nil
			return fmt.Errorf("failed to unmarshal ApplianceSystemOpStatusRelationship as ApplianceSystemOpStatus: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal ApplianceSystemOpStatusRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ApplianceSystemOpStatusRelationship) MarshalJSON() ([]byte, error) {
	if src.ApplianceSystemOpStatus != nil {
		return json.Marshal(&src.ApplianceSystemOpStatus)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ApplianceSystemOpStatusRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ApplianceSystemOpStatus != nil {
		return obj.ApplianceSystemOpStatus
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableApplianceSystemOpStatusRelationship struct {
	value *ApplianceSystemOpStatusRelationship
	isSet bool
}

func (v NullableApplianceSystemOpStatusRelationship) Get() *ApplianceSystemOpStatusRelationship {
	return v.value
}

func (v *NullableApplianceSystemOpStatusRelationship) Set(val *ApplianceSystemOpStatusRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableApplianceSystemOpStatusRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableApplianceSystemOpStatusRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplianceSystemOpStatusRelationship(val *ApplianceSystemOpStatusRelationship) *NullableApplianceSystemOpStatusRelationship {
	return &NullableApplianceSystemOpStatusRelationship{value: val, isSet: true}
}

func (v NullableApplianceSystemOpStatusRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplianceSystemOpStatusRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
