/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025020308
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// NiatelemetryLcResponse - The response body of a HTTP GET request for the 'niatelemetry.Lc' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'niatelemetry.Lc' resources.
type NiatelemetryLcResponse struct {
	MoAggregateTransform *MoAggregateTransform
	MoDocumentCount      *MoDocumentCount
	MoTagSummary         *MoTagSummary
	NiatelemetryLcList   *NiatelemetryLcList
}

// MoAggregateTransformAsNiatelemetryLcResponse is a convenience function that returns MoAggregateTransform wrapped in NiatelemetryLcResponse
func MoAggregateTransformAsNiatelemetryLcResponse(v *MoAggregateTransform) NiatelemetryLcResponse {
	return NiatelemetryLcResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsNiatelemetryLcResponse is a convenience function that returns MoDocumentCount wrapped in NiatelemetryLcResponse
func MoDocumentCountAsNiatelemetryLcResponse(v *MoDocumentCount) NiatelemetryLcResponse {
	return NiatelemetryLcResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsNiatelemetryLcResponse is a convenience function that returns MoTagSummary wrapped in NiatelemetryLcResponse
func MoTagSummaryAsNiatelemetryLcResponse(v *MoTagSummary) NiatelemetryLcResponse {
	return NiatelemetryLcResponse{
		MoTagSummary: v,
	}
}

// NiatelemetryLcListAsNiatelemetryLcResponse is a convenience function that returns NiatelemetryLcList wrapped in NiatelemetryLcResponse
func NiatelemetryLcListAsNiatelemetryLcResponse(v *NiatelemetryLcList) NiatelemetryLcResponse {
	return NiatelemetryLcResponse{
		NiatelemetryLcList: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *NiatelemetryLcResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal NiatelemetryLcResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal NiatelemetryLcResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal NiatelemetryLcResponse as MoTagSummary: %s", err.Error())
		}
	}

	// check if the discriminator value is 'niatelemetry.Lc.List'
	if jsonDict["ObjectType"] == "niatelemetry.Lc.List" {
		// try to unmarshal JSON data into NiatelemetryLcList
		err = json.Unmarshal(data, &dst.NiatelemetryLcList)
		if err == nil {
			return nil // data stored in dst.NiatelemetryLcList, return on the first match
		} else {
			dst.NiatelemetryLcList = nil
			return fmt.Errorf("failed to unmarshal NiatelemetryLcResponse as NiatelemetryLcList: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src NiatelemetryLcResponse) MarshalJSON() ([]byte, error) {
	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	if src.NiatelemetryLcList != nil {
		return json.Marshal(&src.NiatelemetryLcList)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *NiatelemetryLcResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	if obj.NiatelemetryLcList != nil {
		return obj.NiatelemetryLcList
	}

	// all schemas are nil
	return nil
}

type NullableNiatelemetryLcResponse struct {
	value *NiatelemetryLcResponse
	isSet bool
}

func (v NullableNiatelemetryLcResponse) Get() *NiatelemetryLcResponse {
	return v.value
}

func (v *NullableNiatelemetryLcResponse) Set(val *NiatelemetryLcResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNiatelemetryLcResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNiatelemetryLcResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNiatelemetryLcResponse(val *NiatelemetryLcResponse) *NullableNiatelemetryLcResponse {
	return &NullableNiatelemetryLcResponse{value: val, isSet: true}
}

func (v NullableNiatelemetryLcResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNiatelemetryLcResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
