/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-14968
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// StorageNetAppAggregateResponse - The response body of a HTTP GET request for the 'storage.NetAppAggregate' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'storage.NetAppAggregate' resources.
type StorageNetAppAggregateResponse struct {
	MoAggregateTransform       *MoAggregateTransform
	MoDocumentCount            *MoDocumentCount
	MoTagSummary               *MoTagSummary
	StorageNetAppAggregateList *StorageNetAppAggregateList
}

// MoAggregateTransformAsStorageNetAppAggregateResponse is a convenience function that returns MoAggregateTransform wrapped in StorageNetAppAggregateResponse
func MoAggregateTransformAsStorageNetAppAggregateResponse(v *MoAggregateTransform) StorageNetAppAggregateResponse {
	return StorageNetAppAggregateResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsStorageNetAppAggregateResponse is a convenience function that returns MoDocumentCount wrapped in StorageNetAppAggregateResponse
func MoDocumentCountAsStorageNetAppAggregateResponse(v *MoDocumentCount) StorageNetAppAggregateResponse {
	return StorageNetAppAggregateResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsStorageNetAppAggregateResponse is a convenience function that returns MoTagSummary wrapped in StorageNetAppAggregateResponse
func MoTagSummaryAsStorageNetAppAggregateResponse(v *MoTagSummary) StorageNetAppAggregateResponse {
	return StorageNetAppAggregateResponse{
		MoTagSummary: v,
	}
}

// StorageNetAppAggregateListAsStorageNetAppAggregateResponse is a convenience function that returns StorageNetAppAggregateList wrapped in StorageNetAppAggregateResponse
func StorageNetAppAggregateListAsStorageNetAppAggregateResponse(v *StorageNetAppAggregateList) StorageNetAppAggregateResponse {
	return StorageNetAppAggregateResponse{
		StorageNetAppAggregateList: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *StorageNetAppAggregateResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal StorageNetAppAggregateResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal StorageNetAppAggregateResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal StorageNetAppAggregateResponse as MoTagSummary: %s", err.Error())
		}
	}

	// check if the discriminator value is 'storage.NetAppAggregate.List'
	if jsonDict["ObjectType"] == "storage.NetAppAggregate.List" {
		// try to unmarshal JSON data into StorageNetAppAggregateList
		err = json.Unmarshal(data, &dst.StorageNetAppAggregateList)
		if err == nil {
			return nil // data stored in dst.StorageNetAppAggregateList, return on the first match
		} else {
			dst.StorageNetAppAggregateList = nil
			return fmt.Errorf("failed to unmarshal StorageNetAppAggregateResponse as StorageNetAppAggregateList: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src StorageNetAppAggregateResponse) MarshalJSON() ([]byte, error) {
	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	if src.StorageNetAppAggregateList != nil {
		return json.Marshal(&src.StorageNetAppAggregateList)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *StorageNetAppAggregateResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	if obj.StorageNetAppAggregateList != nil {
		return obj.StorageNetAppAggregateList
	}

	// all schemas are nil
	return nil
}

type NullableStorageNetAppAggregateResponse struct {
	value *StorageNetAppAggregateResponse
	isSet bool
}

func (v NullableStorageNetAppAggregateResponse) Get() *StorageNetAppAggregateResponse {
	return v.value
}

func (v *NullableStorageNetAppAggregateResponse) Set(val *StorageNetAppAggregateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageNetAppAggregateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageNetAppAggregateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageNetAppAggregateResponse(val *StorageNetAppAggregateResponse) *NullableStorageNetAppAggregateResponse {
	return &NullableStorageNetAppAggregateResponse{value: val, isSet: true}
}

func (v NullableStorageNetAppAggregateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageNetAppAggregateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
