/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-18369
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// FabricConfigChangeDetailRelationship - A relationship to the 'fabric.ConfigChangeDetail' resource, or the expanded 'fabric.ConfigChangeDetail' resource, or the 'null' value.
type FabricConfigChangeDetailRelationship struct {
	FabricConfigChangeDetail *FabricConfigChangeDetail
	MoMoRef                  *MoMoRef
}

// FabricConfigChangeDetailAsFabricConfigChangeDetailRelationship is a convenience function that returns FabricConfigChangeDetail wrapped in FabricConfigChangeDetailRelationship
func FabricConfigChangeDetailAsFabricConfigChangeDetailRelationship(v *FabricConfigChangeDetail) FabricConfigChangeDetailRelationship {
	return FabricConfigChangeDetailRelationship{
		FabricConfigChangeDetail: v,
	}
}

// MoMoRefAsFabricConfigChangeDetailRelationship is a convenience function that returns MoMoRef wrapped in FabricConfigChangeDetailRelationship
func MoMoRefAsFabricConfigChangeDetailRelationship(v *MoMoRef) FabricConfigChangeDetailRelationship {
	return FabricConfigChangeDetailRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *FabricConfigChangeDetailRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'fabric.ConfigChangeDetail'
	if jsonDict["ClassId"] == "fabric.ConfigChangeDetail" {
		// try to unmarshal JSON data into FabricConfigChangeDetail
		err = json.Unmarshal(data, &dst.FabricConfigChangeDetail)
		if err == nil {
			return nil // data stored in dst.FabricConfigChangeDetail, return on the first match
		} else {
			dst.FabricConfigChangeDetail = nil
			return fmt.Errorf("failed to unmarshal FabricConfigChangeDetailRelationship as FabricConfigChangeDetail: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal FabricConfigChangeDetailRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FabricConfigChangeDetailRelationship) MarshalJSON() ([]byte, error) {
	if src.FabricConfigChangeDetail != nil {
		return json.Marshal(&src.FabricConfigChangeDetail)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FabricConfigChangeDetailRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FabricConfigChangeDetail != nil {
		return obj.FabricConfigChangeDetail
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableFabricConfigChangeDetailRelationship struct {
	value *FabricConfigChangeDetailRelationship
	isSet bool
}

func (v NullableFabricConfigChangeDetailRelationship) Get() *FabricConfigChangeDetailRelationship {
	return v.value
}

func (v *NullableFabricConfigChangeDetailRelationship) Set(val *FabricConfigChangeDetailRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableFabricConfigChangeDetailRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableFabricConfigChangeDetailRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFabricConfigChangeDetailRelationship(val *FabricConfigChangeDetailRelationship) *NullableFabricConfigChangeDetailRelationship {
	return &NullableFabricConfigChangeDetailRelationship{value: val, isSet: true}
}

func (v NullableFabricConfigChangeDetailRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFabricConfigChangeDetailRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
