/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025101412
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// EquipmentChassisControllerRelationship - A relationship to the 'equipment.ChassisController' resource, or the expanded 'equipment.ChassisController' resource, or the 'null' value.
type EquipmentChassisControllerRelationship struct {
	EquipmentChassisController *EquipmentChassisController
	MoMoRef                    *MoMoRef
}

// EquipmentChassisControllerAsEquipmentChassisControllerRelationship is a convenience function that returns EquipmentChassisController wrapped in EquipmentChassisControllerRelationship
func EquipmentChassisControllerAsEquipmentChassisControllerRelationship(v *EquipmentChassisController) EquipmentChassisControllerRelationship {
	return EquipmentChassisControllerRelationship{
		EquipmentChassisController: v,
	}
}

// MoMoRefAsEquipmentChassisControllerRelationship is a convenience function that returns MoMoRef wrapped in EquipmentChassisControllerRelationship
func MoMoRefAsEquipmentChassisControllerRelationship(v *MoMoRef) EquipmentChassisControllerRelationship {
	return EquipmentChassisControllerRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *EquipmentChassisControllerRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'equipment.ChassisController'
	if jsonDict["ClassId"] == "equipment.ChassisController" {
		// try to unmarshal JSON data into EquipmentChassisController
		err = json.Unmarshal(data, &dst.EquipmentChassisController)
		if err == nil {
			return nil // data stored in dst.EquipmentChassisController, return on the first match
		} else {
			dst.EquipmentChassisController = nil
			return fmt.Errorf("failed to unmarshal EquipmentChassisControllerRelationship as EquipmentChassisController: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal EquipmentChassisControllerRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src EquipmentChassisControllerRelationship) MarshalJSON() ([]byte, error) {
	if src.EquipmentChassisController != nil {
		return json.Marshal(&src.EquipmentChassisController)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *EquipmentChassisControllerRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.EquipmentChassisController != nil {
		return obj.EquipmentChassisController
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableEquipmentChassisControllerRelationship struct {
	value *EquipmentChassisControllerRelationship
	isSet bool
}

func (v NullableEquipmentChassisControllerRelationship) Get() *EquipmentChassisControllerRelationship {
	return v.value
}

func (v *NullableEquipmentChassisControllerRelationship) Set(val *EquipmentChassisControllerRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableEquipmentChassisControllerRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableEquipmentChassisControllerRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEquipmentChassisControllerRelationship(val *EquipmentChassisControllerRelationship) *NullableEquipmentChassisControllerRelationship {
	return &NullableEquipmentChassisControllerRelationship{value: val, isSet: true}
}

func (v NullableEquipmentChassisControllerRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEquipmentChassisControllerRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
