/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2026072720
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// NiatelemetrySwitchResponse - The response body of a HTTP GET request for the 'niatelemetry.Switch' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'niatelemetry.Switch' resources.
type NiatelemetrySwitchResponse struct {
	MoAggregateTransform   *MoAggregateTransform
	MoDocumentCount        *MoDocumentCount
	MoTagSummary           *MoTagSummary
	NiatelemetrySwitchList *NiatelemetrySwitchList
}

// MoAggregateTransformAsNiatelemetrySwitchResponse is a convenience function that returns MoAggregateTransform wrapped in NiatelemetrySwitchResponse
func MoAggregateTransformAsNiatelemetrySwitchResponse(v *MoAggregateTransform) NiatelemetrySwitchResponse {
	return NiatelemetrySwitchResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsNiatelemetrySwitchResponse is a convenience function that returns MoDocumentCount wrapped in NiatelemetrySwitchResponse
func MoDocumentCountAsNiatelemetrySwitchResponse(v *MoDocumentCount) NiatelemetrySwitchResponse {
	return NiatelemetrySwitchResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsNiatelemetrySwitchResponse is a convenience function that returns MoTagSummary wrapped in NiatelemetrySwitchResponse
func MoTagSummaryAsNiatelemetrySwitchResponse(v *MoTagSummary) NiatelemetrySwitchResponse {
	return NiatelemetrySwitchResponse{
		MoTagSummary: v,
	}
}

// NiatelemetrySwitchListAsNiatelemetrySwitchResponse is a convenience function that returns NiatelemetrySwitchList wrapped in NiatelemetrySwitchResponse
func NiatelemetrySwitchListAsNiatelemetrySwitchResponse(v *NiatelemetrySwitchList) NiatelemetrySwitchResponse {
	return NiatelemetrySwitchResponse{
		NiatelemetrySwitchList: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *NiatelemetrySwitchResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal NiatelemetrySwitchResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal NiatelemetrySwitchResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal NiatelemetrySwitchResponse as MoTagSummary: %s", err.Error())
		}
	}

	// check if the discriminator value is 'niatelemetry.Switch.List'
	if jsonDict["ObjectType"] == "niatelemetry.Switch.List" {
		// try to unmarshal JSON data into NiatelemetrySwitchList
		err = json.Unmarshal(data, &dst.NiatelemetrySwitchList)
		if err == nil {
			return nil // data stored in dst.NiatelemetrySwitchList, return on the first match
		} else {
			dst.NiatelemetrySwitchList = nil
			return fmt.Errorf("failed to unmarshal NiatelemetrySwitchResponse as NiatelemetrySwitchList: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src NiatelemetrySwitchResponse) MarshalJSON() ([]byte, error) {
	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	if src.NiatelemetrySwitchList != nil {
		return json.Marshal(&src.NiatelemetrySwitchList)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *NiatelemetrySwitchResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	if obj.NiatelemetrySwitchList != nil {
		return obj.NiatelemetrySwitchList
	}

	// all schemas are nil
	return nil
}

type NullableNiatelemetrySwitchResponse struct {
	value *NiatelemetrySwitchResponse
	isSet bool
}

func (v NullableNiatelemetrySwitchResponse) Get() *NiatelemetrySwitchResponse {
	return v.value
}

func (v *NullableNiatelemetrySwitchResponse) Set(val *NiatelemetrySwitchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNiatelemetrySwitchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNiatelemetrySwitchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNiatelemetrySwitchResponse(val *NiatelemetrySwitchResponse) *NullableNiatelemetrySwitchResponse {
	return &NullableNiatelemetrySwitchResponse{value: val, isSet: true}
}

func (v NullableNiatelemetrySwitchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNiatelemetrySwitchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
