/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025030309
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// IamEndPointRoleRelationship - A relationship to the 'iam.EndPointRole' resource, or the expanded 'iam.EndPointRole' resource, or the 'null' value.
type IamEndPointRoleRelationship struct {
	IamEndPointRole *IamEndPointRole
	MoMoRef         *MoMoRef
}

// IamEndPointRoleAsIamEndPointRoleRelationship is a convenience function that returns IamEndPointRole wrapped in IamEndPointRoleRelationship
func IamEndPointRoleAsIamEndPointRoleRelationship(v *IamEndPointRole) IamEndPointRoleRelationship {
	return IamEndPointRoleRelationship{
		IamEndPointRole: v,
	}
}

// MoMoRefAsIamEndPointRoleRelationship is a convenience function that returns MoMoRef wrapped in IamEndPointRoleRelationship
func MoMoRefAsIamEndPointRoleRelationship(v *MoMoRef) IamEndPointRoleRelationship {
	return IamEndPointRoleRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *IamEndPointRoleRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'iam.EndPointRole'
	if jsonDict["ClassId"] == "iam.EndPointRole" {
		// try to unmarshal JSON data into IamEndPointRole
		err = json.Unmarshal(data, &dst.IamEndPointRole)
		if err == nil {
			return nil // data stored in dst.IamEndPointRole, return on the first match
		} else {
			dst.IamEndPointRole = nil
			return fmt.Errorf("failed to unmarshal IamEndPointRoleRelationship as IamEndPointRole: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal IamEndPointRoleRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src IamEndPointRoleRelationship) MarshalJSON() ([]byte, error) {
	if src.IamEndPointRole != nil {
		return json.Marshal(&src.IamEndPointRole)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *IamEndPointRoleRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.IamEndPointRole != nil {
		return obj.IamEndPointRole
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableIamEndPointRoleRelationship struct {
	value *IamEndPointRoleRelationship
	isSet bool
}

func (v NullableIamEndPointRoleRelationship) Get() *IamEndPointRoleRelationship {
	return v.value
}

func (v *NullableIamEndPointRoleRelationship) Set(val *IamEndPointRoleRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableIamEndPointRoleRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableIamEndPointRoleRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIamEndPointRoleRelationship(val *IamEndPointRoleRelationship) *NullableIamEndPointRoleRelationship {
	return &NullableIamEndPointRoleRelationship{value: val, isSet: true}
}

func (v NullableIamEndPointRoleRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIamEndPointRoleRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
