/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025040411
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// VirtualizationVmwareUplinkPortResponse - The response body of a HTTP GET request for the 'virtualization.VmwareUplinkPort' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'virtualization.VmwareUplinkPort' resources.
type VirtualizationVmwareUplinkPortResponse struct {
	MoAggregateTransform               *MoAggregateTransform
	MoDocumentCount                    *MoDocumentCount
	MoTagSummary                       *MoTagSummary
	VirtualizationVmwareUplinkPortList *VirtualizationVmwareUplinkPortList
}

// MoAggregateTransformAsVirtualizationVmwareUplinkPortResponse is a convenience function that returns MoAggregateTransform wrapped in VirtualizationVmwareUplinkPortResponse
func MoAggregateTransformAsVirtualizationVmwareUplinkPortResponse(v *MoAggregateTransform) VirtualizationVmwareUplinkPortResponse {
	return VirtualizationVmwareUplinkPortResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsVirtualizationVmwareUplinkPortResponse is a convenience function that returns MoDocumentCount wrapped in VirtualizationVmwareUplinkPortResponse
func MoDocumentCountAsVirtualizationVmwareUplinkPortResponse(v *MoDocumentCount) VirtualizationVmwareUplinkPortResponse {
	return VirtualizationVmwareUplinkPortResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsVirtualizationVmwareUplinkPortResponse is a convenience function that returns MoTagSummary wrapped in VirtualizationVmwareUplinkPortResponse
func MoTagSummaryAsVirtualizationVmwareUplinkPortResponse(v *MoTagSummary) VirtualizationVmwareUplinkPortResponse {
	return VirtualizationVmwareUplinkPortResponse{
		MoTagSummary: v,
	}
}

// VirtualizationVmwareUplinkPortListAsVirtualizationVmwareUplinkPortResponse is a convenience function that returns VirtualizationVmwareUplinkPortList wrapped in VirtualizationVmwareUplinkPortResponse
func VirtualizationVmwareUplinkPortListAsVirtualizationVmwareUplinkPortResponse(v *VirtualizationVmwareUplinkPortList) VirtualizationVmwareUplinkPortResponse {
	return VirtualizationVmwareUplinkPortResponse{
		VirtualizationVmwareUplinkPortList: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *VirtualizationVmwareUplinkPortResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal VirtualizationVmwareUplinkPortResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal VirtualizationVmwareUplinkPortResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal VirtualizationVmwareUplinkPortResponse as MoTagSummary: %s", err.Error())
		}
	}

	// check if the discriminator value is 'virtualization.VmwareUplinkPort.List'
	if jsonDict["ObjectType"] == "virtualization.VmwareUplinkPort.List" {
		// try to unmarshal JSON data into VirtualizationVmwareUplinkPortList
		err = json.Unmarshal(data, &dst.VirtualizationVmwareUplinkPortList)
		if err == nil {
			return nil // data stored in dst.VirtualizationVmwareUplinkPortList, return on the first match
		} else {
			dst.VirtualizationVmwareUplinkPortList = nil
			return fmt.Errorf("failed to unmarshal VirtualizationVmwareUplinkPortResponse as VirtualizationVmwareUplinkPortList: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VirtualizationVmwareUplinkPortResponse) MarshalJSON() ([]byte, error) {
	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	if src.VirtualizationVmwareUplinkPortList != nil {
		return json.Marshal(&src.VirtualizationVmwareUplinkPortList)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *VirtualizationVmwareUplinkPortResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	if obj.VirtualizationVmwareUplinkPortList != nil {
		return obj.VirtualizationVmwareUplinkPortList
	}

	// all schemas are nil
	return nil
}

type NullableVirtualizationVmwareUplinkPortResponse struct {
	value *VirtualizationVmwareUplinkPortResponse
	isSet bool
}

func (v NullableVirtualizationVmwareUplinkPortResponse) Get() *VirtualizationVmwareUplinkPortResponse {
	return v.value
}

func (v *NullableVirtualizationVmwareUplinkPortResponse) Set(val *VirtualizationVmwareUplinkPortResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualizationVmwareUplinkPortResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualizationVmwareUplinkPortResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualizationVmwareUplinkPortResponse(val *VirtualizationVmwareUplinkPortResponse) *NullableVirtualizationVmwareUplinkPortResponse {
	return &NullableVirtualizationVmwareUplinkPortResponse{value: val, isSet: true}
}

func (v NullableVirtualizationVmwareUplinkPortResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualizationVmwareUplinkPortResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
