/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-18012
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// CapabilityServerUpgradeSupportMetaResponse - The response body of a HTTP GET request for the 'capability.ServerUpgradeSupportMeta' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'capability.ServerUpgradeSupportMeta' resources.
type CapabilityServerUpgradeSupportMetaResponse struct {
	CapabilityServerUpgradeSupportMetaList *CapabilityServerUpgradeSupportMetaList
	MoAggregateTransform                   *MoAggregateTransform
	MoDocumentCount                        *MoDocumentCount
	MoTagSummary                           *MoTagSummary
}

// CapabilityServerUpgradeSupportMetaListAsCapabilityServerUpgradeSupportMetaResponse is a convenience function that returns CapabilityServerUpgradeSupportMetaList wrapped in CapabilityServerUpgradeSupportMetaResponse
func CapabilityServerUpgradeSupportMetaListAsCapabilityServerUpgradeSupportMetaResponse(v *CapabilityServerUpgradeSupportMetaList) CapabilityServerUpgradeSupportMetaResponse {
	return CapabilityServerUpgradeSupportMetaResponse{
		CapabilityServerUpgradeSupportMetaList: v,
	}
}

// MoAggregateTransformAsCapabilityServerUpgradeSupportMetaResponse is a convenience function that returns MoAggregateTransform wrapped in CapabilityServerUpgradeSupportMetaResponse
func MoAggregateTransformAsCapabilityServerUpgradeSupportMetaResponse(v *MoAggregateTransform) CapabilityServerUpgradeSupportMetaResponse {
	return CapabilityServerUpgradeSupportMetaResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsCapabilityServerUpgradeSupportMetaResponse is a convenience function that returns MoDocumentCount wrapped in CapabilityServerUpgradeSupportMetaResponse
func MoDocumentCountAsCapabilityServerUpgradeSupportMetaResponse(v *MoDocumentCount) CapabilityServerUpgradeSupportMetaResponse {
	return CapabilityServerUpgradeSupportMetaResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsCapabilityServerUpgradeSupportMetaResponse is a convenience function that returns MoTagSummary wrapped in CapabilityServerUpgradeSupportMetaResponse
func MoTagSummaryAsCapabilityServerUpgradeSupportMetaResponse(v *MoTagSummary) CapabilityServerUpgradeSupportMetaResponse {
	return CapabilityServerUpgradeSupportMetaResponse{
		MoTagSummary: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CapabilityServerUpgradeSupportMetaResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'capability.ServerUpgradeSupportMeta.List'
	if jsonDict["ObjectType"] == "capability.ServerUpgradeSupportMeta.List" {
		// try to unmarshal JSON data into CapabilityServerUpgradeSupportMetaList
		err = json.Unmarshal(data, &dst.CapabilityServerUpgradeSupportMetaList)
		if err == nil {
			return nil // data stored in dst.CapabilityServerUpgradeSupportMetaList, return on the first match
		} else {
			dst.CapabilityServerUpgradeSupportMetaList = nil
			return fmt.Errorf("failed to unmarshal CapabilityServerUpgradeSupportMetaResponse as CapabilityServerUpgradeSupportMetaList: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal CapabilityServerUpgradeSupportMetaResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal CapabilityServerUpgradeSupportMetaResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal CapabilityServerUpgradeSupportMetaResponse as MoTagSummary: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CapabilityServerUpgradeSupportMetaResponse) MarshalJSON() ([]byte, error) {
	if src.CapabilityServerUpgradeSupportMetaList != nil {
		return json.Marshal(&src.CapabilityServerUpgradeSupportMetaList)
	}

	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CapabilityServerUpgradeSupportMetaResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CapabilityServerUpgradeSupportMetaList != nil {
		return obj.CapabilityServerUpgradeSupportMetaList
	}

	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	// all schemas are nil
	return nil
}

type NullableCapabilityServerUpgradeSupportMetaResponse struct {
	value *CapabilityServerUpgradeSupportMetaResponse
	isSet bool
}

func (v NullableCapabilityServerUpgradeSupportMetaResponse) Get() *CapabilityServerUpgradeSupportMetaResponse {
	return v.value
}

func (v *NullableCapabilityServerUpgradeSupportMetaResponse) Set(val *CapabilityServerUpgradeSupportMetaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCapabilityServerUpgradeSupportMetaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCapabilityServerUpgradeSupportMetaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapabilityServerUpgradeSupportMetaResponse(val *CapabilityServerUpgradeSupportMetaResponse) *NullableCapabilityServerUpgradeSupportMetaResponse {
	return &NullableCapabilityServerUpgradeSupportMetaResponse{value: val, isSet: true}
}

func (v NullableCapabilityServerUpgradeSupportMetaResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapabilityServerUpgradeSupportMetaResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
