/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025062323
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// HciClusterRelationship - A relationship to the 'hci.Cluster' resource, or the expanded 'hci.Cluster' resource, or the 'null' value.
type HciClusterRelationship struct {
	HciCluster *HciCluster
	MoMoRef    *MoMoRef
}

// HciClusterAsHciClusterRelationship is a convenience function that returns HciCluster wrapped in HciClusterRelationship
func HciClusterAsHciClusterRelationship(v *HciCluster) HciClusterRelationship {
	return HciClusterRelationship{
		HciCluster: v,
	}
}

// MoMoRefAsHciClusterRelationship is a convenience function that returns MoMoRef wrapped in HciClusterRelationship
func MoMoRefAsHciClusterRelationship(v *MoMoRef) HciClusterRelationship {
	return HciClusterRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *HciClusterRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'hci.Cluster'
	if jsonDict["ClassId"] == "hci.Cluster" {
		// try to unmarshal JSON data into HciCluster
		err = json.Unmarshal(data, &dst.HciCluster)
		if err == nil {
			return nil // data stored in dst.HciCluster, return on the first match
		} else {
			dst.HciCluster = nil
			return fmt.Errorf("failed to unmarshal HciClusterRelationship as HciCluster: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal HciClusterRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src HciClusterRelationship) MarshalJSON() ([]byte, error) {
	if src.HciCluster != nil {
		return json.Marshal(&src.HciCluster)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *HciClusterRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.HciCluster != nil {
		return obj.HciCluster
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableHciClusterRelationship struct {
	value *HciClusterRelationship
	isSet bool
}

func (v NullableHciClusterRelationship) Get() *HciClusterRelationship {
	return v.value
}

func (v *NullableHciClusterRelationship) Set(val *HciClusterRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableHciClusterRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableHciClusterRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHciClusterRelationship(val *HciClusterRelationship) *NullableHciClusterRelationship {
	return &NullableHciClusterRelationship{value: val, isSet: true}
}

func (v NullableHciClusterRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHciClusterRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
