/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025101412
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// StoragePureHostLunResponse - The response body of a HTTP GET request for the 'storage.PureHostLun' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'storage.PureHostLun' resources.
type StoragePureHostLunResponse struct {
	MoAggregateTransform   *MoAggregateTransform
	MoDocumentCount        *MoDocumentCount
	MoTagSummary           *MoTagSummary
	StoragePureHostLunList *StoragePureHostLunList
}

// MoAggregateTransformAsStoragePureHostLunResponse is a convenience function that returns MoAggregateTransform wrapped in StoragePureHostLunResponse
func MoAggregateTransformAsStoragePureHostLunResponse(v *MoAggregateTransform) StoragePureHostLunResponse {
	return StoragePureHostLunResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsStoragePureHostLunResponse is a convenience function that returns MoDocumentCount wrapped in StoragePureHostLunResponse
func MoDocumentCountAsStoragePureHostLunResponse(v *MoDocumentCount) StoragePureHostLunResponse {
	return StoragePureHostLunResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsStoragePureHostLunResponse is a convenience function that returns MoTagSummary wrapped in StoragePureHostLunResponse
func MoTagSummaryAsStoragePureHostLunResponse(v *MoTagSummary) StoragePureHostLunResponse {
	return StoragePureHostLunResponse{
		MoTagSummary: v,
	}
}

// StoragePureHostLunListAsStoragePureHostLunResponse is a convenience function that returns StoragePureHostLunList wrapped in StoragePureHostLunResponse
func StoragePureHostLunListAsStoragePureHostLunResponse(v *StoragePureHostLunList) StoragePureHostLunResponse {
	return StoragePureHostLunResponse{
		StoragePureHostLunList: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *StoragePureHostLunResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal StoragePureHostLunResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal StoragePureHostLunResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal StoragePureHostLunResponse as MoTagSummary: %s", err.Error())
		}
	}

	// check if the discriminator value is 'storage.PureHostLun.List'
	if jsonDict["ObjectType"] == "storage.PureHostLun.List" {
		// try to unmarshal JSON data into StoragePureHostLunList
		err = json.Unmarshal(data, &dst.StoragePureHostLunList)
		if err == nil {
			return nil // data stored in dst.StoragePureHostLunList, return on the first match
		} else {
			dst.StoragePureHostLunList = nil
			return fmt.Errorf("failed to unmarshal StoragePureHostLunResponse as StoragePureHostLunList: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src StoragePureHostLunResponse) MarshalJSON() ([]byte, error) {
	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	if src.StoragePureHostLunList != nil {
		return json.Marshal(&src.StoragePureHostLunList)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *StoragePureHostLunResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	if obj.StoragePureHostLunList != nil {
		return obj.StoragePureHostLunList
	}

	// all schemas are nil
	return nil
}

type NullableStoragePureHostLunResponse struct {
	value *StoragePureHostLunResponse
	isSet bool
}

func (v NullableStoragePureHostLunResponse) Get() *StoragePureHostLunResponse {
	return v.value
}

func (v *NullableStoragePureHostLunResponse) Set(val *StoragePureHostLunResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStoragePureHostLunResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStoragePureHostLunResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoragePureHostLunResponse(val *StoragePureHostLunResponse) *NullableStoragePureHostLunResponse {
	return &NullableStoragePureHostLunResponse{value: val, isSet: true}
}

func (v NullableStoragePureHostLunResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoragePureHostLunResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
