/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025051220
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// ApplianceDeviceStateResponse - The response body of a HTTP GET request for the 'appliance.DeviceState' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'appliance.DeviceState' resources.
type ApplianceDeviceStateResponse struct {
	ApplianceDeviceStateList *ApplianceDeviceStateList
	MoAggregateTransform     *MoAggregateTransform
	MoDocumentCount          *MoDocumentCount
	MoTagSummary             *MoTagSummary
}

// ApplianceDeviceStateListAsApplianceDeviceStateResponse is a convenience function that returns ApplianceDeviceStateList wrapped in ApplianceDeviceStateResponse
func ApplianceDeviceStateListAsApplianceDeviceStateResponse(v *ApplianceDeviceStateList) ApplianceDeviceStateResponse {
	return ApplianceDeviceStateResponse{
		ApplianceDeviceStateList: v,
	}
}

// MoAggregateTransformAsApplianceDeviceStateResponse is a convenience function that returns MoAggregateTransform wrapped in ApplianceDeviceStateResponse
func MoAggregateTransformAsApplianceDeviceStateResponse(v *MoAggregateTransform) ApplianceDeviceStateResponse {
	return ApplianceDeviceStateResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsApplianceDeviceStateResponse is a convenience function that returns MoDocumentCount wrapped in ApplianceDeviceStateResponse
func MoDocumentCountAsApplianceDeviceStateResponse(v *MoDocumentCount) ApplianceDeviceStateResponse {
	return ApplianceDeviceStateResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsApplianceDeviceStateResponse is a convenience function that returns MoTagSummary wrapped in ApplianceDeviceStateResponse
func MoTagSummaryAsApplianceDeviceStateResponse(v *MoTagSummary) ApplianceDeviceStateResponse {
	return ApplianceDeviceStateResponse{
		MoTagSummary: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ApplianceDeviceStateResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'appliance.DeviceState.List'
	if jsonDict["ObjectType"] == "appliance.DeviceState.List" {
		// try to unmarshal JSON data into ApplianceDeviceStateList
		err = json.Unmarshal(data, &dst.ApplianceDeviceStateList)
		if err == nil {
			return nil // data stored in dst.ApplianceDeviceStateList, return on the first match
		} else {
			dst.ApplianceDeviceStateList = nil
			return fmt.Errorf("failed to unmarshal ApplianceDeviceStateResponse as ApplianceDeviceStateList: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal ApplianceDeviceStateResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal ApplianceDeviceStateResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal ApplianceDeviceStateResponse as MoTagSummary: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ApplianceDeviceStateResponse) MarshalJSON() ([]byte, error) {
	if src.ApplianceDeviceStateList != nil {
		return json.Marshal(&src.ApplianceDeviceStateList)
	}

	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ApplianceDeviceStateResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ApplianceDeviceStateList != nil {
		return obj.ApplianceDeviceStateList
	}

	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	// all schemas are nil
	return nil
}

type NullableApplianceDeviceStateResponse struct {
	value *ApplianceDeviceStateResponse
	isSet bool
}

func (v NullableApplianceDeviceStateResponse) Get() *ApplianceDeviceStateResponse {
	return v.value
}

func (v *NullableApplianceDeviceStateResponse) Set(val *ApplianceDeviceStateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApplianceDeviceStateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApplianceDeviceStateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplianceDeviceStateResponse(val *ApplianceDeviceStateResponse) *NullableApplianceDeviceStateResponse {
	return &NullableApplianceDeviceStateResponse{value: val, isSet: true}
}

func (v NullableApplianceDeviceStateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplianceDeviceStateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
