/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025021903
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// VirtualizationVmwarePhysicalNetworkInterfaceResponse - The response body of a HTTP GET request for the 'virtualization.VmwarePhysicalNetworkInterface' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'virtualization.VmwarePhysicalNetworkInterface' resources.
type VirtualizationVmwarePhysicalNetworkInterfaceResponse struct {
	MoAggregateTransform                             *MoAggregateTransform
	MoDocumentCount                                  *MoDocumentCount
	MoTagSummary                                     *MoTagSummary
	VirtualizationVmwarePhysicalNetworkInterfaceList *VirtualizationVmwarePhysicalNetworkInterfaceList
}

// MoAggregateTransformAsVirtualizationVmwarePhysicalNetworkInterfaceResponse is a convenience function that returns MoAggregateTransform wrapped in VirtualizationVmwarePhysicalNetworkInterfaceResponse
func MoAggregateTransformAsVirtualizationVmwarePhysicalNetworkInterfaceResponse(v *MoAggregateTransform) VirtualizationVmwarePhysicalNetworkInterfaceResponse {
	return VirtualizationVmwarePhysicalNetworkInterfaceResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsVirtualizationVmwarePhysicalNetworkInterfaceResponse is a convenience function that returns MoDocumentCount wrapped in VirtualizationVmwarePhysicalNetworkInterfaceResponse
func MoDocumentCountAsVirtualizationVmwarePhysicalNetworkInterfaceResponse(v *MoDocumentCount) VirtualizationVmwarePhysicalNetworkInterfaceResponse {
	return VirtualizationVmwarePhysicalNetworkInterfaceResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsVirtualizationVmwarePhysicalNetworkInterfaceResponse is a convenience function that returns MoTagSummary wrapped in VirtualizationVmwarePhysicalNetworkInterfaceResponse
func MoTagSummaryAsVirtualizationVmwarePhysicalNetworkInterfaceResponse(v *MoTagSummary) VirtualizationVmwarePhysicalNetworkInterfaceResponse {
	return VirtualizationVmwarePhysicalNetworkInterfaceResponse{
		MoTagSummary: v,
	}
}

// VirtualizationVmwarePhysicalNetworkInterfaceListAsVirtualizationVmwarePhysicalNetworkInterfaceResponse is a convenience function that returns VirtualizationVmwarePhysicalNetworkInterfaceList wrapped in VirtualizationVmwarePhysicalNetworkInterfaceResponse
func VirtualizationVmwarePhysicalNetworkInterfaceListAsVirtualizationVmwarePhysicalNetworkInterfaceResponse(v *VirtualizationVmwarePhysicalNetworkInterfaceList) VirtualizationVmwarePhysicalNetworkInterfaceResponse {
	return VirtualizationVmwarePhysicalNetworkInterfaceResponse{
		VirtualizationVmwarePhysicalNetworkInterfaceList: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *VirtualizationVmwarePhysicalNetworkInterfaceResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal VirtualizationVmwarePhysicalNetworkInterfaceResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal VirtualizationVmwarePhysicalNetworkInterfaceResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal VirtualizationVmwarePhysicalNetworkInterfaceResponse as MoTagSummary: %s", err.Error())
		}
	}

	// check if the discriminator value is 'virtualization.VmwarePhysicalNetworkInterface.List'
	if jsonDict["ObjectType"] == "virtualization.VmwarePhysicalNetworkInterface.List" {
		// try to unmarshal JSON data into VirtualizationVmwarePhysicalNetworkInterfaceList
		err = json.Unmarshal(data, &dst.VirtualizationVmwarePhysicalNetworkInterfaceList)
		if err == nil {
			return nil // data stored in dst.VirtualizationVmwarePhysicalNetworkInterfaceList, return on the first match
		} else {
			dst.VirtualizationVmwarePhysicalNetworkInterfaceList = nil
			return fmt.Errorf("failed to unmarshal VirtualizationVmwarePhysicalNetworkInterfaceResponse as VirtualizationVmwarePhysicalNetworkInterfaceList: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VirtualizationVmwarePhysicalNetworkInterfaceResponse) MarshalJSON() ([]byte, error) {
	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	if src.VirtualizationVmwarePhysicalNetworkInterfaceList != nil {
		return json.Marshal(&src.VirtualizationVmwarePhysicalNetworkInterfaceList)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *VirtualizationVmwarePhysicalNetworkInterfaceResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	if obj.VirtualizationVmwarePhysicalNetworkInterfaceList != nil {
		return obj.VirtualizationVmwarePhysicalNetworkInterfaceList
	}

	// all schemas are nil
	return nil
}

type NullableVirtualizationVmwarePhysicalNetworkInterfaceResponse struct {
	value *VirtualizationVmwarePhysicalNetworkInterfaceResponse
	isSet bool
}

func (v NullableVirtualizationVmwarePhysicalNetworkInterfaceResponse) Get() *VirtualizationVmwarePhysicalNetworkInterfaceResponse {
	return v.value
}

func (v *NullableVirtualizationVmwarePhysicalNetworkInterfaceResponse) Set(val *VirtualizationVmwarePhysicalNetworkInterfaceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualizationVmwarePhysicalNetworkInterfaceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualizationVmwarePhysicalNetworkInterfaceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualizationVmwarePhysicalNetworkInterfaceResponse(val *VirtualizationVmwarePhysicalNetworkInterfaceResponse) *NullableVirtualizationVmwarePhysicalNetworkInterfaceResponse {
	return &NullableVirtualizationVmwarePhysicalNetworkInterfaceResponse{value: val, isSet: true}
}

func (v NullableVirtualizationVmwarePhysicalNetworkInterfaceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualizationVmwarePhysicalNetworkInterfaceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
