/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2026072720
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// CapabilityTimeZoneMetaDataResponse - The response body of a HTTP GET request for the 'capability.TimeZoneMetaData' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'capability.TimeZoneMetaData' resources.
type CapabilityTimeZoneMetaDataResponse struct {
	CapabilityTimeZoneMetaDataList *CapabilityTimeZoneMetaDataList
	MoAggregateTransform           *MoAggregateTransform
	MoDocumentCount                *MoDocumentCount
	MoTagSummary                   *MoTagSummary
}

// CapabilityTimeZoneMetaDataListAsCapabilityTimeZoneMetaDataResponse is a convenience function that returns CapabilityTimeZoneMetaDataList wrapped in CapabilityTimeZoneMetaDataResponse
func CapabilityTimeZoneMetaDataListAsCapabilityTimeZoneMetaDataResponse(v *CapabilityTimeZoneMetaDataList) CapabilityTimeZoneMetaDataResponse {
	return CapabilityTimeZoneMetaDataResponse{
		CapabilityTimeZoneMetaDataList: v,
	}
}

// MoAggregateTransformAsCapabilityTimeZoneMetaDataResponse is a convenience function that returns MoAggregateTransform wrapped in CapabilityTimeZoneMetaDataResponse
func MoAggregateTransformAsCapabilityTimeZoneMetaDataResponse(v *MoAggregateTransform) CapabilityTimeZoneMetaDataResponse {
	return CapabilityTimeZoneMetaDataResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsCapabilityTimeZoneMetaDataResponse is a convenience function that returns MoDocumentCount wrapped in CapabilityTimeZoneMetaDataResponse
func MoDocumentCountAsCapabilityTimeZoneMetaDataResponse(v *MoDocumentCount) CapabilityTimeZoneMetaDataResponse {
	return CapabilityTimeZoneMetaDataResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsCapabilityTimeZoneMetaDataResponse is a convenience function that returns MoTagSummary wrapped in CapabilityTimeZoneMetaDataResponse
func MoTagSummaryAsCapabilityTimeZoneMetaDataResponse(v *MoTagSummary) CapabilityTimeZoneMetaDataResponse {
	return CapabilityTimeZoneMetaDataResponse{
		MoTagSummary: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CapabilityTimeZoneMetaDataResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'capability.TimeZoneMetaData.List'
	if jsonDict["ObjectType"] == "capability.TimeZoneMetaData.List" {
		// try to unmarshal JSON data into CapabilityTimeZoneMetaDataList
		err = json.Unmarshal(data, &dst.CapabilityTimeZoneMetaDataList)
		if err == nil {
			return nil // data stored in dst.CapabilityTimeZoneMetaDataList, return on the first match
		} else {
			dst.CapabilityTimeZoneMetaDataList = nil
			return fmt.Errorf("failed to unmarshal CapabilityTimeZoneMetaDataResponse as CapabilityTimeZoneMetaDataList: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal CapabilityTimeZoneMetaDataResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal CapabilityTimeZoneMetaDataResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal CapabilityTimeZoneMetaDataResponse as MoTagSummary: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CapabilityTimeZoneMetaDataResponse) MarshalJSON() ([]byte, error) {
	if src.CapabilityTimeZoneMetaDataList != nil {
		return json.Marshal(&src.CapabilityTimeZoneMetaDataList)
	}

	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CapabilityTimeZoneMetaDataResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CapabilityTimeZoneMetaDataList != nil {
		return obj.CapabilityTimeZoneMetaDataList
	}

	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	// all schemas are nil
	return nil
}

type NullableCapabilityTimeZoneMetaDataResponse struct {
	value *CapabilityTimeZoneMetaDataResponse
	isSet bool
}

func (v NullableCapabilityTimeZoneMetaDataResponse) Get() *CapabilityTimeZoneMetaDataResponse {
	return v.value
}

func (v *NullableCapabilityTimeZoneMetaDataResponse) Set(val *CapabilityTimeZoneMetaDataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCapabilityTimeZoneMetaDataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCapabilityTimeZoneMetaDataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapabilityTimeZoneMetaDataResponse(val *CapabilityTimeZoneMetaDataResponse) *NullableCapabilityTimeZoneMetaDataResponse {
	return &NullableCapabilityTimeZoneMetaDataResponse{value: val, isSet: true}
}

func (v NullableCapabilityTimeZoneMetaDataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapabilityTimeZoneMetaDataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
