/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-16342
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// ResourceReservationRelationship - A relationship to the 'resource.Reservation' resource, or the expanded 'resource.Reservation' resource, or the 'null' value.
type ResourceReservationRelationship struct {
	MoMoRef             *MoMoRef
	ResourceReservation *ResourceReservation
}

// MoMoRefAsResourceReservationRelationship is a convenience function that returns MoMoRef wrapped in ResourceReservationRelationship
func MoMoRefAsResourceReservationRelationship(v *MoMoRef) ResourceReservationRelationship {
	return ResourceReservationRelationship{
		MoMoRef: v,
	}
}

// ResourceReservationAsResourceReservationRelationship is a convenience function that returns ResourceReservation wrapped in ResourceReservationRelationship
func ResourceReservationAsResourceReservationRelationship(v *ResourceReservation) ResourceReservationRelationship {
	return ResourceReservationRelationship{
		ResourceReservation: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ResourceReservationRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal ResourceReservationRelationship as MoMoRef: %s", err.Error())
		}
	}

	// check if the discriminator value is 'resource.Reservation'
	if jsonDict["ClassId"] == "resource.Reservation" {
		// try to unmarshal JSON data into ResourceReservation
		err = json.Unmarshal(data, &dst.ResourceReservation)
		if err == nil {
			return nil // data stored in dst.ResourceReservation, return on the first match
		} else {
			dst.ResourceReservation = nil
			return fmt.Errorf("failed to unmarshal ResourceReservationRelationship as ResourceReservation: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ResourceReservationRelationship) MarshalJSON() ([]byte, error) {
	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	if src.ResourceReservation != nil {
		return json.Marshal(&src.ResourceReservation)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ResourceReservationRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	if obj.ResourceReservation != nil {
		return obj.ResourceReservation
	}

	// all schemas are nil
	return nil
}

type NullableResourceReservationRelationship struct {
	value *ResourceReservationRelationship
	isSet bool
}

func (v NullableResourceReservationRelationship) Get() *ResourceReservationRelationship {
	return v.value
}

func (v *NullableResourceReservationRelationship) Set(val *ResourceReservationRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceReservationRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceReservationRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceReservationRelationship(val *ResourceReservationRelationship) *NullableResourceReservationRelationship {
	return &NullableResourceReservationRelationship{value: val, isSet: true}
}

func (v NullableResourceReservationRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceReservationRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
