/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025101412
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// ApplianceGroupOpStatusRelationship - A relationship to the 'appliance.GroupOpStatus' resource, or the expanded 'appliance.GroupOpStatus' resource, or the 'null' value.
type ApplianceGroupOpStatusRelationship struct {
	ApplianceGroupOpStatus *ApplianceGroupOpStatus
	MoMoRef                *MoMoRef
}

// ApplianceGroupOpStatusAsApplianceGroupOpStatusRelationship is a convenience function that returns ApplianceGroupOpStatus wrapped in ApplianceGroupOpStatusRelationship
func ApplianceGroupOpStatusAsApplianceGroupOpStatusRelationship(v *ApplianceGroupOpStatus) ApplianceGroupOpStatusRelationship {
	return ApplianceGroupOpStatusRelationship{
		ApplianceGroupOpStatus: v,
	}
}

// MoMoRefAsApplianceGroupOpStatusRelationship is a convenience function that returns MoMoRef wrapped in ApplianceGroupOpStatusRelationship
func MoMoRefAsApplianceGroupOpStatusRelationship(v *MoMoRef) ApplianceGroupOpStatusRelationship {
	return ApplianceGroupOpStatusRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ApplianceGroupOpStatusRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'appliance.GroupOpStatus'
	if jsonDict["ClassId"] == "appliance.GroupOpStatus" {
		// try to unmarshal JSON data into ApplianceGroupOpStatus
		err = json.Unmarshal(data, &dst.ApplianceGroupOpStatus)
		if err == nil {
			return nil // data stored in dst.ApplianceGroupOpStatus, return on the first match
		} else {
			dst.ApplianceGroupOpStatus = nil
			return fmt.Errorf("failed to unmarshal ApplianceGroupOpStatusRelationship as ApplianceGroupOpStatus: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal ApplianceGroupOpStatusRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ApplianceGroupOpStatusRelationship) MarshalJSON() ([]byte, error) {
	if src.ApplianceGroupOpStatus != nil {
		return json.Marshal(&src.ApplianceGroupOpStatus)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ApplianceGroupOpStatusRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ApplianceGroupOpStatus != nil {
		return obj.ApplianceGroupOpStatus
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableApplianceGroupOpStatusRelationship struct {
	value *ApplianceGroupOpStatusRelationship
	isSet bool
}

func (v NullableApplianceGroupOpStatusRelationship) Get() *ApplianceGroupOpStatusRelationship {
	return v.value
}

func (v *NullableApplianceGroupOpStatusRelationship) Set(val *ApplianceGroupOpStatusRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableApplianceGroupOpStatusRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableApplianceGroupOpStatusRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplianceGroupOpStatusRelationship(val *ApplianceGroupOpStatusRelationship) *NullableApplianceGroupOpStatusRelationship {
	return &NullableApplianceGroupOpStatusRelationship{value: val, isSet: true}
}

func (v NullableApplianceGroupOpStatusRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplianceGroupOpStatusRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
