/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-18775
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// ConvergedinfraPodRelationship - A relationship to the 'convergedinfra.Pod' resource, or the expanded 'convergedinfra.Pod' resource, or the 'null' value.
type ConvergedinfraPodRelationship struct {
	ConvergedinfraPod *ConvergedinfraPod
	MoMoRef           *MoMoRef
}

// ConvergedinfraPodAsConvergedinfraPodRelationship is a convenience function that returns ConvergedinfraPod wrapped in ConvergedinfraPodRelationship
func ConvergedinfraPodAsConvergedinfraPodRelationship(v *ConvergedinfraPod) ConvergedinfraPodRelationship {
	return ConvergedinfraPodRelationship{
		ConvergedinfraPod: v,
	}
}

// MoMoRefAsConvergedinfraPodRelationship is a convenience function that returns MoMoRef wrapped in ConvergedinfraPodRelationship
func MoMoRefAsConvergedinfraPodRelationship(v *MoMoRef) ConvergedinfraPodRelationship {
	return ConvergedinfraPodRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ConvergedinfraPodRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'convergedinfra.Pod'
	if jsonDict["ClassId"] == "convergedinfra.Pod" {
		// try to unmarshal JSON data into ConvergedinfraPod
		err = json.Unmarshal(data, &dst.ConvergedinfraPod)
		if err == nil {
			return nil // data stored in dst.ConvergedinfraPod, return on the first match
		} else {
			dst.ConvergedinfraPod = nil
			return fmt.Errorf("failed to unmarshal ConvergedinfraPodRelationship as ConvergedinfraPod: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal ConvergedinfraPodRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ConvergedinfraPodRelationship) MarshalJSON() ([]byte, error) {
	if src.ConvergedinfraPod != nil {
		return json.Marshal(&src.ConvergedinfraPod)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ConvergedinfraPodRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ConvergedinfraPod != nil {
		return obj.ConvergedinfraPod
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableConvergedinfraPodRelationship struct {
	value *ConvergedinfraPodRelationship
	isSet bool
}

func (v NullableConvergedinfraPodRelationship) Get() *ConvergedinfraPodRelationship {
	return v.value
}

func (v *NullableConvergedinfraPodRelationship) Set(val *ConvergedinfraPodRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableConvergedinfraPodRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableConvergedinfraPodRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConvergedinfraPodRelationship(val *ConvergedinfraPodRelationship) *NullableConvergedinfraPodRelationship {
	return &NullableConvergedinfraPodRelationship{value: val, isSet: true}
}

func (v NullableConvergedinfraPodRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConvergedinfraPodRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
