/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-17057
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// HyperflexClusterBackupPolicyInventoryRelationship - A relationship to the 'hyperflex.ClusterBackupPolicyInventory' resource, or the expanded 'hyperflex.ClusterBackupPolicyInventory' resource, or the 'null' value.
type HyperflexClusterBackupPolicyInventoryRelationship struct {
	HyperflexClusterBackupPolicyInventory *HyperflexClusterBackupPolicyInventory
	MoMoRef                               *MoMoRef
}

// HyperflexClusterBackupPolicyInventoryAsHyperflexClusterBackupPolicyInventoryRelationship is a convenience function that returns HyperflexClusterBackupPolicyInventory wrapped in HyperflexClusterBackupPolicyInventoryRelationship
func HyperflexClusterBackupPolicyInventoryAsHyperflexClusterBackupPolicyInventoryRelationship(v *HyperflexClusterBackupPolicyInventory) HyperflexClusterBackupPolicyInventoryRelationship {
	return HyperflexClusterBackupPolicyInventoryRelationship{
		HyperflexClusterBackupPolicyInventory: v,
	}
}

// MoMoRefAsHyperflexClusterBackupPolicyInventoryRelationship is a convenience function that returns MoMoRef wrapped in HyperflexClusterBackupPolicyInventoryRelationship
func MoMoRefAsHyperflexClusterBackupPolicyInventoryRelationship(v *MoMoRef) HyperflexClusterBackupPolicyInventoryRelationship {
	return HyperflexClusterBackupPolicyInventoryRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *HyperflexClusterBackupPolicyInventoryRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'hyperflex.ClusterBackupPolicyInventory'
	if jsonDict["ClassId"] == "hyperflex.ClusterBackupPolicyInventory" {
		// try to unmarshal JSON data into HyperflexClusterBackupPolicyInventory
		err = json.Unmarshal(data, &dst.HyperflexClusterBackupPolicyInventory)
		if err == nil {
			return nil // data stored in dst.HyperflexClusterBackupPolicyInventory, return on the first match
		} else {
			dst.HyperflexClusterBackupPolicyInventory = nil
			return fmt.Errorf("failed to unmarshal HyperflexClusterBackupPolicyInventoryRelationship as HyperflexClusterBackupPolicyInventory: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal HyperflexClusterBackupPolicyInventoryRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src HyperflexClusterBackupPolicyInventoryRelationship) MarshalJSON() ([]byte, error) {
	if src.HyperflexClusterBackupPolicyInventory != nil {
		return json.Marshal(&src.HyperflexClusterBackupPolicyInventory)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *HyperflexClusterBackupPolicyInventoryRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.HyperflexClusterBackupPolicyInventory != nil {
		return obj.HyperflexClusterBackupPolicyInventory
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableHyperflexClusterBackupPolicyInventoryRelationship struct {
	value *HyperflexClusterBackupPolicyInventoryRelationship
	isSet bool
}

func (v NullableHyperflexClusterBackupPolicyInventoryRelationship) Get() *HyperflexClusterBackupPolicyInventoryRelationship {
	return v.value
}

func (v *NullableHyperflexClusterBackupPolicyInventoryRelationship) Set(val *HyperflexClusterBackupPolicyInventoryRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableHyperflexClusterBackupPolicyInventoryRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableHyperflexClusterBackupPolicyInventoryRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHyperflexClusterBackupPolicyInventoryRelationship(val *HyperflexClusterBackupPolicyInventoryRelationship) *NullableHyperflexClusterBackupPolicyInventoryRelationship {
	return &NullableHyperflexClusterBackupPolicyInventoryRelationship{value: val, isSet: true}
}

func (v NullableHyperflexClusterBackupPolicyInventoryRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHyperflexClusterBackupPolicyInventoryRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
