/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025030309
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// MacpoolIdBlockRelationship - A relationship to the 'macpool.IdBlock' resource, or the expanded 'macpool.IdBlock' resource, or the 'null' value.
type MacpoolIdBlockRelationship struct {
	MacpoolIdBlock *MacpoolIdBlock
	MoMoRef        *MoMoRef
}

// MacpoolIdBlockAsMacpoolIdBlockRelationship is a convenience function that returns MacpoolIdBlock wrapped in MacpoolIdBlockRelationship
func MacpoolIdBlockAsMacpoolIdBlockRelationship(v *MacpoolIdBlock) MacpoolIdBlockRelationship {
	return MacpoolIdBlockRelationship{
		MacpoolIdBlock: v,
	}
}

// MoMoRefAsMacpoolIdBlockRelationship is a convenience function that returns MoMoRef wrapped in MacpoolIdBlockRelationship
func MoMoRefAsMacpoolIdBlockRelationship(v *MoMoRef) MacpoolIdBlockRelationship {
	return MacpoolIdBlockRelationship{
		MoMoRef: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *MacpoolIdBlockRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'macpool.IdBlock'
	if jsonDict["ClassId"] == "macpool.IdBlock" {
		// try to unmarshal JSON data into MacpoolIdBlock
		err = json.Unmarshal(data, &dst.MacpoolIdBlock)
		if err == nil {
			return nil // data stored in dst.MacpoolIdBlock, return on the first match
		} else {
			dst.MacpoolIdBlock = nil
			return fmt.Errorf("failed to unmarshal MacpoolIdBlockRelationship as MacpoolIdBlock: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal MacpoolIdBlockRelationship as MoMoRef: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MacpoolIdBlockRelationship) MarshalJSON() ([]byte, error) {
	if src.MacpoolIdBlock != nil {
		return json.Marshal(&src.MacpoolIdBlock)
	}

	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *MacpoolIdBlockRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MacpoolIdBlock != nil {
		return obj.MacpoolIdBlock
	}

	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	// all schemas are nil
	return nil
}

type NullableMacpoolIdBlockRelationship struct {
	value *MacpoolIdBlockRelationship
	isSet bool
}

func (v NullableMacpoolIdBlockRelationship) Get() *MacpoolIdBlockRelationship {
	return v.value
}

func (v *NullableMacpoolIdBlockRelationship) Set(val *MacpoolIdBlockRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableMacpoolIdBlockRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableMacpoolIdBlockRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMacpoolIdBlockRelationship(val *MacpoolIdBlockRelationship) *NullableMacpoolIdBlockRelationship {
	return &NullableMacpoolIdBlockRelationship{value: val, isSet: true}
}

func (v NullableMacpoolIdBlockRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMacpoolIdBlockRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
