/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025102807
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// ComputePcieConnectivityPolicyInventoryResponse - The response body of a HTTP GET request for the 'compute.PcieConnectivityPolicyInventory' resource. The value may be one of the following types. 1. When 'tag' is specified in the URL query, the response schema     is a summary of the tag usage. 1. When '$apply' is specified in the URL query, the response schema     is dynamically-generated schema based on the $apply value. 1. When '$count' is specified in the URL query, the response is     a simple object providing the count of the resources. 1. In all other cases, the response is a list of 'compute.PcieConnectivityPolicyInventory' resources.
type ComputePcieConnectivityPolicyInventoryResponse struct {
	ComputePcieConnectivityPolicyInventoryList *ComputePcieConnectivityPolicyInventoryList
	MoAggregateTransform                       *MoAggregateTransform
	MoDocumentCount                            *MoDocumentCount
	MoTagSummary                               *MoTagSummary
}

// ComputePcieConnectivityPolicyInventoryListAsComputePcieConnectivityPolicyInventoryResponse is a convenience function that returns ComputePcieConnectivityPolicyInventoryList wrapped in ComputePcieConnectivityPolicyInventoryResponse
func ComputePcieConnectivityPolicyInventoryListAsComputePcieConnectivityPolicyInventoryResponse(v *ComputePcieConnectivityPolicyInventoryList) ComputePcieConnectivityPolicyInventoryResponse {
	return ComputePcieConnectivityPolicyInventoryResponse{
		ComputePcieConnectivityPolicyInventoryList: v,
	}
}

// MoAggregateTransformAsComputePcieConnectivityPolicyInventoryResponse is a convenience function that returns MoAggregateTransform wrapped in ComputePcieConnectivityPolicyInventoryResponse
func MoAggregateTransformAsComputePcieConnectivityPolicyInventoryResponse(v *MoAggregateTransform) ComputePcieConnectivityPolicyInventoryResponse {
	return ComputePcieConnectivityPolicyInventoryResponse{
		MoAggregateTransform: v,
	}
}

// MoDocumentCountAsComputePcieConnectivityPolicyInventoryResponse is a convenience function that returns MoDocumentCount wrapped in ComputePcieConnectivityPolicyInventoryResponse
func MoDocumentCountAsComputePcieConnectivityPolicyInventoryResponse(v *MoDocumentCount) ComputePcieConnectivityPolicyInventoryResponse {
	return ComputePcieConnectivityPolicyInventoryResponse{
		MoDocumentCount: v,
	}
}

// MoTagSummaryAsComputePcieConnectivityPolicyInventoryResponse is a convenience function that returns MoTagSummary wrapped in ComputePcieConnectivityPolicyInventoryResponse
func MoTagSummaryAsComputePcieConnectivityPolicyInventoryResponse(v *MoTagSummary) ComputePcieConnectivityPolicyInventoryResponse {
	return ComputePcieConnectivityPolicyInventoryResponse{
		MoTagSummary: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ComputePcieConnectivityPolicyInventoryResponse) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'compute.PcieConnectivityPolicyInventory.List'
	if jsonDict["ObjectType"] == "compute.PcieConnectivityPolicyInventory.List" {
		// try to unmarshal JSON data into ComputePcieConnectivityPolicyInventoryList
		err = json.Unmarshal(data, &dst.ComputePcieConnectivityPolicyInventoryList)
		if err == nil {
			return nil // data stored in dst.ComputePcieConnectivityPolicyInventoryList, return on the first match
		} else {
			dst.ComputePcieConnectivityPolicyInventoryList = nil
			return fmt.Errorf("failed to unmarshal ComputePcieConnectivityPolicyInventoryResponse as ComputePcieConnectivityPolicyInventoryList: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.AggregateTransform'
	if jsonDict["ObjectType"] == "mo.AggregateTransform" {
		// try to unmarshal JSON data into MoAggregateTransform
		err = json.Unmarshal(data, &dst.MoAggregateTransform)
		if err == nil {
			return nil // data stored in dst.MoAggregateTransform, return on the first match
		} else {
			dst.MoAggregateTransform = nil
			return fmt.Errorf("failed to unmarshal ComputePcieConnectivityPolicyInventoryResponse as MoAggregateTransform: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.DocumentCount'
	if jsonDict["ObjectType"] == "mo.DocumentCount" {
		// try to unmarshal JSON data into MoDocumentCount
		err = json.Unmarshal(data, &dst.MoDocumentCount)
		if err == nil {
			return nil // data stored in dst.MoDocumentCount, return on the first match
		} else {
			dst.MoDocumentCount = nil
			return fmt.Errorf("failed to unmarshal ComputePcieConnectivityPolicyInventoryResponse as MoDocumentCount: %s", err.Error())
		}
	}

	// check if the discriminator value is 'mo.TagSummary'
	if jsonDict["ObjectType"] == "mo.TagSummary" {
		// try to unmarshal JSON data into MoTagSummary
		err = json.Unmarshal(data, &dst.MoTagSummary)
		if err == nil {
			return nil // data stored in dst.MoTagSummary, return on the first match
		} else {
			dst.MoTagSummary = nil
			return fmt.Errorf("failed to unmarshal ComputePcieConnectivityPolicyInventoryResponse as MoTagSummary: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ComputePcieConnectivityPolicyInventoryResponse) MarshalJSON() ([]byte, error) {
	if src.ComputePcieConnectivityPolicyInventoryList != nil {
		return json.Marshal(&src.ComputePcieConnectivityPolicyInventoryList)
	}

	if src.MoAggregateTransform != nil {
		return json.Marshal(&src.MoAggregateTransform)
	}

	if src.MoDocumentCount != nil {
		return json.Marshal(&src.MoDocumentCount)
	}

	if src.MoTagSummary != nil {
		return json.Marshal(&src.MoTagSummary)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ComputePcieConnectivityPolicyInventoryResponse) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ComputePcieConnectivityPolicyInventoryList != nil {
		return obj.ComputePcieConnectivityPolicyInventoryList
	}

	if obj.MoAggregateTransform != nil {
		return obj.MoAggregateTransform
	}

	if obj.MoDocumentCount != nil {
		return obj.MoDocumentCount
	}

	if obj.MoTagSummary != nil {
		return obj.MoTagSummary
	}

	// all schemas are nil
	return nil
}

type NullableComputePcieConnectivityPolicyInventoryResponse struct {
	value *ComputePcieConnectivityPolicyInventoryResponse
	isSet bool
}

func (v NullableComputePcieConnectivityPolicyInventoryResponse) Get() *ComputePcieConnectivityPolicyInventoryResponse {
	return v.value
}

func (v *NullableComputePcieConnectivityPolicyInventoryResponse) Set(val *ComputePcieConnectivityPolicyInventoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComputePcieConnectivityPolicyInventoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComputePcieConnectivityPolicyInventoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputePcieConnectivityPolicyInventoryResponse(val *ComputePcieConnectivityPolicyInventoryResponse) *NullableComputePcieConnectivityPolicyInventoryResponse {
	return &NullableComputePcieConnectivityPolicyInventoryResponse{value: val, isSet: true}
}

func (v NullableComputePcieConnectivityPolicyInventoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputePcieConnectivityPolicyInventoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
