/*
Cisco Intersight

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.11-2025092610
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
)

// StoragePureFileSystemsRelationship - A relationship to the 'storage.PureFileSystems' resource, or the expanded 'storage.PureFileSystems' resource, or the 'null' value.
type StoragePureFileSystemsRelationship struct {
	MoMoRef                *MoMoRef
	StoragePureFileSystems *StoragePureFileSystems
}

// MoMoRefAsStoragePureFileSystemsRelationship is a convenience function that returns MoMoRef wrapped in StoragePureFileSystemsRelationship
func MoMoRefAsStoragePureFileSystemsRelationship(v *MoMoRef) StoragePureFileSystemsRelationship {
	return StoragePureFileSystemsRelationship{
		MoMoRef: v,
	}
}

// StoragePureFileSystemsAsStoragePureFileSystemsRelationship is a convenience function that returns StoragePureFileSystems wrapped in StoragePureFileSystemsRelationship
func StoragePureFileSystemsAsStoragePureFileSystemsRelationship(v *StoragePureFileSystems) StoragePureFileSystemsRelationship {
	return StoragePureFileSystemsRelationship{
		StoragePureFileSystems: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *StoragePureFileSystemsRelationship) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'mo.MoRef'
	if jsonDict["ClassId"] == "mo.MoRef" {
		// try to unmarshal JSON data into MoMoRef
		err = json.Unmarshal(data, &dst.MoMoRef)
		if err == nil {
			return nil // data stored in dst.MoMoRef, return on the first match
		} else {
			dst.MoMoRef = nil
			return fmt.Errorf("failed to unmarshal StoragePureFileSystemsRelationship as MoMoRef: %s", err.Error())
		}
	}

	// check if the discriminator value is 'storage.PureFileSystems'
	if jsonDict["ClassId"] == "storage.PureFileSystems" {
		// try to unmarshal JSON data into StoragePureFileSystems
		err = json.Unmarshal(data, &dst.StoragePureFileSystems)
		if err == nil {
			return nil // data stored in dst.StoragePureFileSystems, return on the first match
		} else {
			dst.StoragePureFileSystems = nil
			return fmt.Errorf("failed to unmarshal StoragePureFileSystemsRelationship as StoragePureFileSystems: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src StoragePureFileSystemsRelationship) MarshalJSON() ([]byte, error) {
	if src.MoMoRef != nil {
		return json.Marshal(&src.MoMoRef)
	}

	if src.StoragePureFileSystems != nil {
		return json.Marshal(&src.StoragePureFileSystems)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *StoragePureFileSystemsRelationship) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MoMoRef != nil {
		return obj.MoMoRef
	}

	if obj.StoragePureFileSystems != nil {
		return obj.StoragePureFileSystems
	}

	// all schemas are nil
	return nil
}

type NullableStoragePureFileSystemsRelationship struct {
	value *StoragePureFileSystemsRelationship
	isSet bool
}

func (v NullableStoragePureFileSystemsRelationship) Get() *StoragePureFileSystemsRelationship {
	return v.value
}

func (v *NullableStoragePureFileSystemsRelationship) Set(val *StoragePureFileSystemsRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableStoragePureFileSystemsRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableStoragePureFileSystemsRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoragePureFileSystemsRelationship(val *StoragePureFileSystemsRelationship) *NullableStoragePureFileSystemsRelationship {
	return &NullableStoragePureFileSystemsRelationship{value: val, isSet: true}
}

func (v NullableStoragePureFileSystemsRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoragePureFileSystemsRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
